In [1]:
import pandas as pd
import scipy.stats
import numpy as np
import time
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# start_time = time.time()
start_time = pd.datetime.now()

In [3]:
data = pd.read_csv('applications data.csv')

In [4]:
data = data[['record','date','ssn','firstname','lastname','address','zip5','dob','homephone','fraud_label']]
data.shape

(1000000, 10)

In [5]:
data.dtypes

record          int64
date            int64
ssn             int64
firstname      object
lastname       object
address        object
zip5            int64
dob             int64
homephone       int64
fraud_label     int64
dtype: object

In [6]:
data['date'] = pd.to_datetime(data['date'])
data.head()

,record,date,ssn,firstname,lastname,address,zip5,dob,homephone,fraud_label
0,1,1970-01-01 00:00:00.020160101,379070012,XRRAMMTR,SMJETJMJ,6861 EUTST PL,2765,19070626,1797504115,0
1,2,1970-01-01 00:00:00.020160101,387482503,MAMSTUJR,RTTEMRRR,7280 URASA PL,57169,19340615,4164239415,1
2,3,1970-01-01 00:00:00.020160101,200332444,SZMMUJEZS,EUSEZRAE,5581 RSREX LN,56721,19070626,216537580,0
3,4,1970-01-01 00:00:00.020160101,747451317,SJJZSXRSZ,ETJXTXXS,1387 UJZXJ RD,35286,19440430,132144161,0
4,5,1970-01-01 00:00:00.020160101,24065868,SSSXUEJMS,SSUUJXUZ,279 EAASA WY,3173,19980315,6101082272,0

In [7]:
data.dtypes

record                  int64
date           datetime64[ns]
ssn                     int64
firstname              object
lastname               object
address                object
zip5                    int64
dob                     int64
homephone               int64
fraud_label             int64
dtype: object

In [8]:
y = data[['record','fraud_label']]
y.head()

   record  fraud_label
0       1            0
1       2            1
2       3            0
3       4            0
4       5            0

In [9]:
y.sum()

record         500000500000
fraud_label           14393
dtype: int64

In [10]:
data['fulladdress'] = data['address'] + ' ' + data['zip5'].astype('str')

In [11]:
data = data.drop(columns = ['zip5', 'address'])

In [12]:
data['ndob'] = data['firstname'].astype('str') + data['lastname'].astype('str') + data['dob'].astype('str')

In [13]:
data.head(10)

,record,date,ssn,firstname,lastname,dob,homephone,fraud_label,fulladdress,ndob
0,1,1970-01-01 00:00:00.020160101,379070012,XRRAMMTR,SMJETJMJ,19070626,1797504115,0,6861 EUTST PL 2765,XRRAMMTRSMJETJMJ19070626
1,2,1970-01-01 00:00:00.020160101,387482503,MAMSTUJR,RTTEMRRR,19340615,4164239415,1,7280 URASA PL 57169,MAMSTUJRRTTEMRRR19340615
2,3,1970-01-01 00:00:00.020160101,200332444,SZMMUJEZS,EUSEZRAE,19070626,216537580,0,5581 RSREX LN 56721,SZMMUJEZSEUSEZRAE19070626
3,4,1970-01-01 00:00:00.020160101,747451317,SJJZSXRSZ,ETJXTXXS,19440430,132144161,0,1387 UJZXJ RD 35286,SJJZSXRSZETJXTXXS19440430
4,5,1970-01-01 00:00:00.020160101,24065868,SSSXUEJMS,SSUUJXUZ,19980315,6101082272,0,279 EAASA WY 3173,SSSXUEJMSSSUUJXUZ19980315
5,6,1970-01-01 00:00:00.020160101,922264214,XEEJJSTER,ERJSAXA,19480613,5742016319,0,4322 USJXU LN 8391,XEEJJSTERERJSAXA19480613
6,7,1970-01-01 00:00:00.020160101,415812149,XZJRJUSRR,STSMJRUM,19640318,7697396312,0,478 EEXUM LN 41640,XZJRJUSRRSTSMJRUM19640318
7,8,1970-01-01 00:00:00.020160101,373752050,EJMRRSUXR,AMTZXRU,19190528,2727421586,0,8906 UUAJ PL 60567,EJMRRSUXRAMTZXRU19190528
8,9,1970-01-01 00:00:00.020160101,769970791,RXTSZJATS,RSXMRJME,19900314,5520652307,0,8266 SSEAR RD 37934,RXTSZJATSRSXMRJME19900314
9,10,1970-01-01 00:00:00.020160101,732119085,EREMTZXXA,EXMMSEXT,19750127,3749451123,0,9166 XXSAZ PL 93751,EREMTZXXAEXMMSEXT19750127

In [14]:
data.shape

(1000000, 10)

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 10 columns):
record         1000000 non-null int64
date           1000000 non-null datetime64[ns]
ssn            1000000 non-null int64
firstname      1000000 non-null object
lastname       1000000 non-null object
dob            1000000 non-null int64
homephone      1000000 non-null int64
fraud_label    1000000 non-null int64
fulladdress    1000000 non-null object
ndob           1000000 non-null object
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 76.3+ MB

In [16]:
# Delete this line when running for real
# data = data.iloc[0:10000:50,:]
# data.shape

In [17]:
data.tail()

,record,date,ssn,firstname,lastname,dob,homephone,fraud_label,fulladdress,ndob
999995,999996,1970-01-01 00:00:00.020161231,766104848,XUSAAURMZ,EJXXEXZX,19550418,8236558223,0,8079 EJRUJ AVE 54890,XUSAAURMZEJXXEXZX19550418
999996,999997,1970-01-01 00:00:00.020161231,445178058,SAAJJEMTX,UMAUETJX,19150624,6790134432,0,4817 UMSXT AVE 74683,SAAJJEMTXUMAUETJX19150624
999997,999998,1970-01-01 00:00:00.020161231,25283410,ESRXXRSUX,EUEJRJJE,19880628,3997657622,0,7562 RJMAZ ST 86805,ESRXXRSUXEUEJRJJE19880628
999998,999999,1970-01-01 00:00:00.020161231,361232148,XXMZSRXMA,RSRSUJSS,20120302,5935293731,0,3408 UZZAM WY 49183,XXMZSRXMARSRSUJSS20120302
999999,1000000,1970-01-01 00:00:00.020161231,40027083,RXZXSMEZA,UTEAAZXU,19820826,5869926905,0,112 UTTJT PL 39491,RXZXSMEZAUTEAAZXU19820826

# Build Variables

In [18]:
data_orig = data.copy()

In [19]:
data['apps_by_s'] = data.groupby(['ssn', 'date']).cumcount() + 1

In [20]:
data['apps_by_a'] = data.groupby(['fulladdress', 'date']).cumcount() + 1

In [21]:
data['apps_by_ndob'] = data.groupby(['ndob', 'date']).cumcount() + 1

In [22]:
data['apps_by_p'] = data.groupby(['homephone', 'date']).cumcount() + 1

In [23]:
data['apps_by_sa'] = data.groupby(['ssn', 'fulladdress', 'date']).cumcount() + 1

In [24]:
data['apps_by_nda'] = data.groupby(['ndob', 'fulladdress', 'date']).cumcount() + 1

In [25]:
data['apps_by_pa'] = data.groupby(['homephone', 'fulladdress', 'date']).cumcount() + 1

In [26]:
data['apps_by_ndp'] = data.groupby(['ndob', 'homephone', 'date']).cumcount() + 1

In [27]:
data['apps_by_ap'] = data.groupby(['fulladdress', 'homephone', 'date']).cumcount() + 1

In [28]:
data['apps_by_ps'] = data.groupby(['homephone', 'ssn', 'date']).cumcount() + 1

In [29]:
data['apps_by_nds'] = data.groupby(['ndob', 'ssn', 'date']).cumcount() + 1

In [30]:
data['apps_by_snd'] = data.groupby(['ssn', 'ndob', 'date']).cumcount() + 1

In [31]:
data['apps_by_fns'] = data.groupby(['firstname', 'ssn', 'date']).cumcount() + 1

In [32]:
data['apps_by_lns'] = data.groupby(['lastname', 'ssn', 'date']).cumcount() + 1

In [33]:
data.head(20).transpose()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
record,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
date,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101,1970-01-01 00:00:00.020160101
ssn,379070012,387482503,200332444,747451317,24065868,922264214,415812149,373752050,769970791,732119085,999999999,854773981,283419783,800705980,654640127,763049287,610654961,346374636,722620451,892971652
firstname,XRRAMMTR,MAMSTUJR,SZMMUJEZS,SJJZSXRSZ,SSSXUEJMS,XEEJJSTER,XZJRJUSRR,EJMRRSUXR,RXTSZJATS,EREMTZXXA,UZZSMXSEE,RSZXMZRSU,EJAASJXXM,MUTAEUUZS,SUXZRSUZT,XAREMEUUU,UJSRSMUEZ,XRSSZZUXT,UXJSUXJUJ,XUTMSSREZ
lastname,SMJETJMJ,RTTEMRRR,EUSEZRAE,ETJXTXXS,SSUUJXUZ,ERJSAXA,STSMJRUM,AMTZXRU,RSXMRJME,EXMMSEXT,USJZUSA,EZJAXJTZ,UZZSAZJR,STAZJXRA,UAJRRXM,SXXJSARX,SJATAXXX,ETXZXJAJ,UUMRUSA,UJEUUJXT
dob,19070626,19340615,19070626,19440430,19980315,19480613,19640318,19190528,19900314,19750127,19400126,19471211,19000122,19400902,19360829,19991228,20080401,19500110,19901113,20060815
homephone,1797504115,4164239415,216537580,132144161,6101082272,5742016319,7697396312,2727421586,5520652307,3749451123,3026547212,3896260651,5874359299,3903104222,1754954648,3915611901,516200670,9999999999,439009868,1938458945
fraud_label,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
fulladdress,6861 EUTST PL 2765,7280 URASA PL 57169,5581 RSREX LN 56721,1387 UJZXJ RD 35286,279 EAASA WY 3173,4322 USJXU LN 8391,478 EEXUM LN 41640,8906 UUAJ PL 60567,8266 SSEAR RD 37934,9166 XXSAZ PL 93751,726 UMTXU ST 92129,2561 RXJXU BLVD 9531,4365 UMXZA LN 82369,1683 RSEJM ST 66204,4961 RTZJA BLVD 61344,6575 EXZXA RD 43912,4057 SRZAE BLVD 29576,5719 UEZJT PL 51486,1198 XAZZR PL 93301,2350 EZTXX AVE 25166
ndob,XRRAMMTRSMJETJMJ19070626,MAMSTUJRRTTEMRRR19340615,SZMMUJEZSEUSEZRAE19070626,SJJZSXRSZETJXTXXS19440430,SSSXUEJMSSSUUJXUZ19980315,XEEJJSTERERJSAXA19480613,XZJRJUSRRSTSMJRUM19640318,EJMRRSUXRAMTZXRU19190528,RXTSZJATSRSXMRJME19900314,EREMTZXXAEXMMSEXT19750127,UZZSMXSEEUSJZUSA19400126,RSZXMZRSUEZJAXJTZ19471211,EJAASJXXMUZZSAZJR19000122,MUTAEUUZSSTAZJXRA19400902,SUXZRSUZTUAJRRXM19360829,XAREMEUUUSXXJSARX19991228,UJSRSMUEZSJATAXXX20080401,XRSSZZUXTETXZXJAJ19500110,UXJSUXJUJUUMRUSA19901113,XUTMSSREZUJEUUJXT20060815
apps_by_s,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_a,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_ndob,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_p,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_sa,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_nda,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_pa,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_ndp,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_ap,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_ps,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_nds,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_snd,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_fns,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_lns,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [34]:
data.tail(20).transpose()

,999980,999981,999982,999983,999984,999985,999986,999987,999988,999989,999990,999991,999992,999993,999994,999995,999996,999997,999998,999999
record,999981,999982,999983,999984,999985,999986,999987,999988,999989,999990,999991,999992,999993,999994,999995,999996,999997,999998,999999,1000000
date,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231,1970-01-01 00:00:00.020161231
ssn,338259307,482977071,418455311,943937178,40890134,344823164,546588574,833008021,619227126,430691587,311934855,836715951,138005271,66352989,26797401,766104848,445178058,25283410,361232148,40027083
firstname,RUUUXXJXS,XJUMAUMAZ,XZSZEXZSR,SAEXUZAXX,XSEARXSMM,XERUMJZUU,MUAJZRTR,XTSESMMRE,MSRUAREMU,XSRMRZTAR,UZEEJUUAE,RZTMRMJAT,EATERRSTR,EXURTTMUT,XEJMESRU,XUSAAURMZ,SAAJJEMTX,ESRXXRSUX,XXMZSRXMA,RXZXSMEZA
lastname,RMJZURRS,SXUARMJX,ETERUXME,UTUMJXAJ,EASASTEM,AZMAUU,SSJXTUJM,UAJXEAJU,ETAJXSRE,RSXZSJAT,SXZXJRJT,RJSASESA,UZJTXTS,URMMJMXE,UTATSZUX,EJXXEXZX,UMAUETJX,EUEJRJJE,RSRSUJSS,UTEAAZXU
dob,19490725,19121202,19310831,19570118,19000813,19150701,19640318,20061214,19610225,19070626,19240719,19070626,19490607,19340123,19360313,19550418,19150624,19880628,20120302,19820826
homephone,4826547781,3705354914,1523556940,7628097980,8559088830,3523076355,2930456508,5282198328,6304330265,6102388193,2209569257,9999999999,7559317028,5161204838,6114170353,8236558223,6790134432,3997657622,5935293731,5869926905
fraud_label,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
fulladdress,3075 SEJXS PL 43787,680 XJART AVE 11343,9381 UXMXA WY 59614,9704 UMUXS PL 4890,4187 SMXRS ST 23831,2615 SUMZE AVE 22378,7825 XMSAE RD 25898,1775 XJXE LN 21879,5948 RMZSR ST 48650,980 XTESE WY 77781,3667 SEEMZ PL 12921,3139 SZJAT BLVD 56999,6332 RRAUR RD 23960,3724 UXASM BLVD 43552,2397 SXZEX DR 54964,8079 EJRUJ AVE 54890,4817 UMSXT AVE 74683,7562 RJMAZ ST 86805,3408 UZZAM WY 49183,112 UTTJT PL 39491
ndob,RUUUXXJXSRMJZURRS19490725,XJUMAUMAZSXUARMJX19121202,XZSZEXZSRETERUXME19310831,SAEXUZAXXUTUMJXAJ19570118,XSEARXSMMEASASTEM19000813,XERUMJZUUAZMAUU19150701,MUAJZRTRSSJXTUJM19640318,XTSESMMREUAJXEAJU20061214,MSRUAREMUETAJXSRE19610225,XSRMRZTARRSXZSJAT19070626,UZEEJUUAESXZXJRJT19240719,RZTMRMJATRJSASESA19070626,EATERRSTRUZJTXTS19490607,EXURTTMUTURMMJMXE19340123,XEJMESRUUTATSZUX19360313,XUSAAURMZEJXXEXZX19550418,SAAJJEMTXUMAUETJX19150624,ESRXXRSUXEUEJRJJE19880628,XXMZSRXMARSRSUJSS20120302,RXZXSMEZAUTEAAZXU19820826
apps_by_s,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_a,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_ndob,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_p,1,1,1,1,1,1,1,1,1,2,1,200,1,1,1,1,2,1,1,1
apps_by_sa,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_nda,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_pa,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_ndp,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_ap,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_ps,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_nds,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_snd,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_fns,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
apps_by_lns,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [35]:
data_ref = data.copy()

In [36]:
data_ref = data_ref.set_index('date')

## Velocity Variables

In [37]:
# apps by ssn

napps_s_1 = data_ref.groupby(['ssn'])['record'].rolling('1d').count().reset_index()
napps_s_1['apps_by_s'] = napps_s_1.groupby(['ssn', 'date']).cumcount() + 1

napps_s_3 = data_ref.groupby(['ssn'])['record'].rolling('3d').count().reset_index()
napps_s_3['apps_by_s'] = napps_s_3.groupby(['ssn', 'date']).cumcount() + 1

napps_s_7 = data_ref.groupby(['ssn'])['record'].rolling('7d').count().reset_index()
napps_s_7['apps_by_s'] = napps_s_7.groupby(['ssn', 'date']).cumcount() + 1

napps_s_14 = data_ref.groupby(['ssn'])['record'].rolling('14d').count().reset_index()
napps_s_14['apps_by_s'] = napps_s_14.groupby(['ssn', 'date']).cumcount() + 1

napps_s_30 = data_ref.groupby(['ssn'])['record'].rolling('30d').count().reset_index()
napps_s_30['apps_by_s'] = napps_s_30.groupby(['ssn', 'date']).cumcount() + 1

In [38]:
# apps by address

napps_a_1 = data_ref.groupby(['fulladdress'])['record'].rolling('1d').count().reset_index()
napps_a_1['apps_by_a'] = napps_a_1.groupby(['fulladdress', 'date']).cumcount() + 1

napps_a_3 = data_ref.groupby(['fulladdress'])['record'].rolling('3d').count().reset_index()
napps_a_3['apps_by_a'] = napps_a_3.groupby(['fulladdress', 'date']).cumcount() + 1

napps_a_7 = data_ref.groupby(['fulladdress'])['record'].rolling('7d').count().reset_index()
napps_a_7['apps_by_a'] = napps_a_7.groupby(['fulladdress', 'date']).cumcount() + 1

napps_a_14 = data_ref.groupby(['fulladdress'])['record'].rolling('14d').count().reset_index()
napps_a_14['apps_by_a'] = napps_a_14.groupby(['fulladdress', 'date']).cumcount() + 1

napps_a_30 = data_ref.groupby(['fulladdress'])['record'].rolling('30d').count().reset_index()
napps_a_30['apps_by_a'] = napps_a_30.groupby(['fulladdress', 'date']).cumcount() + 1

In [39]:
# apps by ndob

napps_ndob_1 = data_ref.groupby(['ndob'])['record'].rolling('1d').count().reset_index()
napps_ndob_1['apps_by_ndob'] = napps_ndob_1.groupby(['ndob', 'date']).cumcount() + 1

napps_ndob_3 = data_ref.groupby(['ndob'])['record'].rolling('3d').count().reset_index()
napps_ndob_3['apps_by_ndob'] = napps_ndob_3.groupby(['ndob', 'date']).cumcount() + 1

napps_ndob_7 = data_ref.groupby(['ndob'])['record'].rolling('7d').count().reset_index()
napps_ndob_7['apps_by_ndob'] = napps_ndob_7.groupby(['ndob', 'date']).cumcount() + 1

napps_ndob_14 = data_ref.groupby(['ndob'])['record'].rolling('14d').count().reset_index()
napps_ndob_14['apps_by_ndob'] = napps_ndob_14.groupby(['ndob', 'date']).cumcount() + 1

napps_ndob_30 = data_ref.groupby(['ndob'])['record'].rolling('30d').count().reset_index()
napps_ndob_30['apps_by_ndob'] = napps_ndob_30.groupby(['ndob', 'date']).cumcount() + 1

In [40]:
# apps by phone

napps_p_1 = data_ref.groupby(['homephone'])['record'].rolling('1d').count().reset_index()
napps_p_1['apps_by_p'] = napps_p_1.groupby(['homephone', 'date']).cumcount() + 1

napps_p_3 = data_ref.groupby(['homephone'])['record'].rolling('3d').count().reset_index()
napps_p_3['apps_by_p'] = napps_p_3.groupby(['homephone', 'date']).cumcount() + 1

napps_p_7 = data_ref.groupby(['homephone'])['record'].rolling('7d').count().reset_index()
napps_p_7['apps_by_p'] = napps_p_7.groupby(['homephone', 'date']).cumcount() + 1

napps_p_14 = data_ref.groupby(['homephone'])['record'].rolling('14d').count().reset_index()
napps_p_14['apps_by_p'] = napps_p_14.groupby(['homephone', 'date']).cumcount() + 1

napps_p_30 = data_ref.groupby(['homephone'])['record'].rolling('30d').count().reset_index()
napps_p_30['apps_by_p'] = napps_p_30.groupby(['homephone', 'date']).cumcount() + 1

In [41]:
# apps by ssn and address

napps_sa_1 = data_ref.groupby(['ssn','fulladdress'])['record'].rolling('1d').count().reset_index()
napps_sa_1['apps_by_sa'] = napps_sa_1.groupby(['ssn','fulladdress','date']).cumcount() + 1

napps_sa_3 = data_ref.groupby(['ssn','fulladdress'])['record'].rolling('3d').count().reset_index()
napps_sa_3['apps_by_sa'] = napps_sa_3.groupby(['ssn','fulladdress','date']).cumcount() + 1

napps_sa_7 = data_ref.groupby(['ssn','fulladdress'])['record'].rolling('7d').count().reset_index()
napps_sa_7['apps_by_sa'] = napps_sa_7.groupby(['ssn','fulladdress','date']).cumcount() + 1

napps_sa_14 = data_ref.groupby(['ssn','fulladdress'])['record'].rolling('14d').count().reset_index()
napps_sa_14['apps_by_sa'] = napps_sa_14.groupby(['ssn','fulladdress','date']).cumcount() + 1

napps_sa_30 = data_ref.groupby(['ssn','fulladdress'])['record'].rolling('30d').count().reset_index()
napps_sa_30['apps_by_sa'] = napps_sa_30.groupby(['ssn','fulladdress','date']).cumcount() + 1

In [42]:
# apps by ndob and address

napps_nda_1 = data_ref.groupby(['ndob', 'fulladdress'])['record'].rolling('1d').count().reset_index()
napps_nda_1['apps_by_nda'] = napps_nda_1.groupby(['ndob','fulladdress','date']).cumcount() + 1

napps_nda_3 = data_ref.groupby(['ndob', 'fulladdress'])['record'].rolling('3d').count().reset_index()
napps_nda_3['apps_by_nda'] = napps_nda_3.groupby(['ndob','fulladdress','date']).cumcount() + 1

napps_nda_7 = data_ref.groupby(['ndob', 'fulladdress'])['record'].rolling('7d').count().reset_index()
napps_nda_7['apps_by_nda'] = napps_nda_7.groupby(['ndob','fulladdress','date']).cumcount() + 1

napps_nda_14 = data_ref.groupby(['ndob', 'fulladdress'])['record'].rolling('14d').count().reset_index()
napps_nda_14['apps_by_nda'] = napps_nda_14.groupby(['ndob','fulladdress','date']).cumcount() + 1

napps_nda_30 = data_ref.groupby(['ndob', 'fulladdress'])['record'].rolling('30d').count().reset_index()
napps_nda_30['apps_by_nda'] = napps_nda_30.groupby(['ndob','fulladdress','date']).cumcount() + 1

In [43]:
# apps by phone and address

napps_pa_1 = data_ref.groupby(['homephone','fulladdress'])['record'].rolling('1d').count().reset_index()
napps_pa_1['apps_by_pa'] = napps_pa_1.groupby(['homephone','fulladdress','date']).cumcount() + 1

napps_pa_3 = data_ref.groupby(['homephone','fulladdress'])['record'].rolling('3d').count().reset_index()
napps_pa_3['apps_by_pa'] = napps_pa_3.groupby(['homephone','fulladdress','date']).cumcount() + 1

napps_pa_7 = data_ref.groupby(['homephone','fulladdress'])['record'].rolling('7d').count().reset_index()
napps_pa_7['apps_by_pa'] = napps_pa_7.groupby(['homephone','fulladdress','date']).cumcount() + 1

napps_pa_14 = data_ref.groupby(['homephone','fulladdress'])['record'].rolling('14d').count().reset_index()
napps_pa_14['apps_by_pa'] = napps_pa_14.groupby(['homephone','fulladdress','date']).cumcount() + 1

napps_pa_30 = data_ref.groupby(['homephone','fulladdress'])['record'].rolling('30d').count().reset_index()
napps_pa_30['apps_by_pa'] = napps_pa_30.groupby(['homephone','fulladdress','date']).cumcount() + 1

In [44]:
# apps by ndob and phone

napps_ndp_1 = data_ref.groupby(['ndob','homephone'])['record'].rolling('1d').count().reset_index()
napps_ndp_1['apps_by_ndp'] = napps_ndp_1.groupby(['ndob','homephone','date']).cumcount() + 1

napps_ndp_3 = data_ref.groupby(['ndob','homephone'])['record'].rolling('3d').count().reset_index()
napps_ndp_3['apps_by_ndp'] = napps_ndp_3.groupby(['ndob','homephone','date']).cumcount() + 1

napps_ndp_7 = data_ref.groupby(['ndob','homephone'])['record'].rolling('7d').count().reset_index()
napps_ndp_7['apps_by_ndp'] = napps_ndp_7.groupby(['ndob','homephone','date']).cumcount() + 1

napps_ndp_14 = data_ref.groupby(['ndob','homephone'])['record'].rolling('14d').count().reset_index()
napps_ndp_14['apps_by_ndp'] = napps_ndp_14.groupby(['ndob','homephone','date']).cumcount() + 1

napps_ndp_30 = data_ref.groupby(['ndob','homephone'])['record'].rolling('30d').count().reset_index()
napps_ndp_30['apps_by_ndp'] = napps_ndp_30.groupby(['ndob','homephone','date']).cumcount() + 1

In [45]:
# apps by address and phone

napps_ap_1 = data_ref.groupby(['fulladdress','homephone'])['record'].rolling('1d').count().reset_index()
napps_ap_1['apps_by_ap'] = napps_ap_1.groupby(['fulladdress','homephone','date']).cumcount() + 1

napps_ap_3 = data_ref.groupby(['fulladdress','homephone'])['record'].rolling('3d').count().reset_index()
napps_ap_3['apps_by_ap'] = napps_ap_3.groupby(['fulladdress','homephone','date']).cumcount() + 1

napps_ap_7 = data_ref.groupby(['fulladdress','homephone'])['record'].rolling('7d').count().reset_index()
napps_ap_7['apps_by_ap'] = napps_ap_7.groupby(['fulladdress','homephone','date']).cumcount() + 1

napps_ap_14 = data_ref.groupby(['fulladdress','homephone'])['record'].rolling('14d').count().reset_index()
napps_ap_14['apps_by_ap'] = napps_ap_14.groupby(['fulladdress','homephone','date']).cumcount() + 1

napps_ap_30 = data_ref.groupby(['fulladdress','homephone'])['record'].rolling('30d').count().reset_index()
napps_ap_30['apps_by_ap'] = napps_ap_30.groupby(['fulladdress','homephone','date']).cumcount() + 1

In [46]:
# apps by phone and ssn

napps_ps_1 = data_ref.groupby(['homephone','ssn'])['record'].rolling('1d').count().reset_index()
napps_ps_1['apps_by_ps'] = napps_ps_1.groupby(['homephone','ssn','date']).cumcount() + 1

napps_ps_3 = data_ref.groupby(['homephone','ssn'])['record'].rolling('3d').count().reset_index()
napps_ps_3['apps_by_ps'] = napps_ps_3.groupby(['homephone','ssn','date']).cumcount() + 1

napps_ps_7 = data_ref.groupby(['homephone','ssn'])['record'].rolling('7d').count().reset_index()
napps_ps_7['apps_by_ps'] = napps_ps_7.groupby(['homephone','ssn','date']).cumcount() + 1

napps_ps_14 = data_ref.groupby(['homephone','ssn'])['record'].rolling('14d').count().reset_index()
napps_ps_14['apps_by_ps'] = napps_ps_14.groupby(['homephone','ssn','date']).cumcount() + 1

napps_ps_30 = data_ref.groupby(['homephone','ssn'])['record'].rolling('30d').count().reset_index()
napps_ps_30['apps_by_ps'] = napps_ps_30.groupby(['homephone','ssn','date']).cumcount() + 1

In [47]:
# apps by ndob and ssn

napps_nds_1 = data_ref.groupby(['ndob','ssn'])['record'].rolling('1d').count().reset_index()
napps_nds_1['apps_by_nds'] = napps_nds_1.groupby(['ndob','ssn','date']).cumcount() + 1

napps_nds_3 = data_ref.groupby(['ndob','ssn'])['record'].rolling('3d').count().reset_index()
napps_nds_3['apps_by_nds'] = napps_nds_3.groupby(['ndob','ssn','date']).cumcount() + 1

napps_nds_7 = data_ref.groupby(['ndob','ssn'])['record'].rolling('7d').count().reset_index()
napps_nds_7['apps_by_nds'] = napps_nds_7.groupby(['ndob','ssn','date']).cumcount() + 1

napps_nds_14 = data_ref.groupby(['ndob','ssn'])['record'].rolling('14d').count().reset_index()
napps_nds_14['apps_by_nds'] = napps_nds_14.groupby(['ndob','ssn','date']).cumcount() + 1

napps_nds_30 = data_ref.groupby(['ndob','ssn'])['record'].rolling('30d').count().reset_index()
napps_nds_30['apps_by_nds'] = napps_nds_30.groupby(['ndob','ssn','date']).cumcount() + 1

In [48]:
# apps by ssn and ndob

napps_snd_1 = data_ref.groupby(['ssn','ndob'])['record'].rolling('1d').count().reset_index()
napps_snd_1['apps_by_snd'] = napps_snd_1.groupby(['ssn','ndob','date']).cumcount() + 1

napps_snd_3 = data_ref.groupby(['ssn','ndob'])['record'].rolling('3d').count().reset_index()
napps_snd_3['apps_by_snd'] = napps_snd_3.groupby(['ssn','ndob','date']).cumcount() + 1

napps_snd_7 = data_ref.groupby(['ssn','ndob'])['record'].rolling('7d').count().reset_index()
napps_snd_7['apps_by_snd'] = napps_snd_7.groupby(['ssn','ndob','date']).cumcount() + 1

napps_snd_14 = data_ref.groupby(['ssn','ndob'])['record'].rolling('14d').count().reset_index()
napps_snd_14['apps_by_snd'] = napps_snd_14.groupby(['ssn','ndob','date']).cumcount() + 1

napps_snd_30 = data_ref.groupby(['ssn','ndob'])['record'].rolling('30d').count().reset_index()
napps_snd_30['apps_by_snd'] = napps_snd_30.groupby(['ssn','ndob','date']).cumcount() + 1

In [49]:
# apps by FN and ssn

napps_fns_1 = data_ref.groupby(['firstname','ssn'])['record'].rolling('1d').count().reset_index()
napps_fns_1['apps_by_fns'] = napps_fns_1.groupby(['firstname','ssn','date']).cumcount() + 1

napps_fns_3 = data_ref.groupby(['firstname','ssn'])['record'].rolling('3d').count().reset_index()
napps_fns_3['apps_by_fns'] = napps_fns_3.groupby(['firstname','ssn','date']).cumcount() + 1

napps_fns_7 = data_ref.groupby(['firstname','ssn'])['record'].rolling('7d').count().reset_index()
napps_fns_7['apps_by_fns'] = napps_fns_7.groupby(['firstname','ssn','date']).cumcount() + 1

napps_fns_14 = data_ref.groupby(['firstname','ssn'])['record'].rolling('14d').count().reset_index()
napps_fns_14['apps_by_fns'] = napps_fns_14.groupby(['firstname','ssn','date']).cumcount() + 1

napps_fns_30 = data_ref.groupby(['firstname','ssn'])['record'].rolling('30d').count().reset_index()
napps_fns_30['apps_by_fns'] = napps_fns_30.groupby(['firstname','ssn','date']).cumcount() + 1

In [50]:
# apps by LN ssn

napps_lns_1 = data_ref.groupby(['lastname','ssn'])['record'].rolling('1d').count().reset_index()
napps_lns_1['apps_by_lns'] = napps_lns_1.groupby(['lastname','ssn','date']).cumcount() + 1

napps_lns_3 = data_ref.groupby(['lastname','ssn'])['record'].rolling('3d').count().reset_index()
napps_lns_3['apps_by_lns'] = napps_lns_3.groupby(['lastname','ssn','date']).cumcount() + 1

napps_lns_7 = data_ref.groupby(['lastname','ssn'])['record'].rolling('7d').count().reset_index()
napps_lns_7['apps_by_lns'] = napps_lns_7.groupby(['lastname','ssn','date']).cumcount() + 1

napps_lns_14 = data_ref.groupby(['lastname','ssn'])['record'].rolling('14d').count().reset_index()
napps_lns_14['apps_by_lns'] = napps_lns_14.groupby(['lastname','ssn','date']).cumcount() + 1

napps_lns_30 = data_ref.groupby(['lastname','ssn'])['record'].rolling('30d').count().reset_index()
napps_lns_30['apps_by_lns'] = napps_lns_30.groupby(['lastname','ssn','date']).cumcount() + 1

## Days Since Variables

In [51]:
data_ref = data_ref.reset_index()

In [52]:
def ds(g1, g2, name):
    'Helps with calculating these day since variables'
    day_s = data_ref.groupby(g1)[g1].first()
    day_s = day_s.rename_axis(['None' for i in range(len(g1))]).groupby(g2).diff()
    day_s.columns = [name]
    day_s = day_s.rename_axis(g1)
    day_s[name] = day_s[name].dt.days.fillna(0)
    day_s = day_s.reset_index()
    return day_s

In [53]:
## ssn
day_s = ds(['ssn', 'date'], 'ssn', 'ssn_diff')
# day_s = data_ref.groupby(['ssn', 'date'])['ssn', 'date'].first().groupby('ssn').diff()
# day_s.columns = ['ssn_diff']
# day_s['ssn_diff'] = day_s['ssn_diff'].dt.days.fillna(0)
# day_s = day_s.reset_index()

## address
day_a = ds(['fulladdress', 'date'],'fulladdress', 'address_diff')
#day_a = data_ref.groupby(['fulladdress', 'date'])['fulladdress', 'date'].first().groupby('fulladdress').diff()
#day_a.columns = ['address_diff']
#day_a['address_diff'] = day_a['address_diff'].dt.days.fillna(0)
#day_a = day_a.reset_index()

## phone
day_p = ds(['homephone', 'date'], 'homephone', 'phone_diff')
#day_p = data_ref.groupby(['homephone', 'date'])['homephone', 'date'].first().groupby('homephone').diff()
#day_p.columns = ['phone_diff']
#day_p['phone_diff'] = day_p['phone_diff'].dt.days.fillna(0)
#day_p = day_p.reset_index()

## ndob
day_ndob = ds(['ndob', 'date'], 'ndob', 'ndob_diff')
#day_ndob = data_ref.groupby(['ndob', 'date'])['ndob', 'date'].first().groupby('ndob').diff()
#day_ndob.columns = ['ndob_diff']
#day_ndob['ndob_diff'] = day_ndob['ndob_diff'].dt.days.fillna(0)
#day_ndob = day_ndob.reset_index()

## ssn + address
day_sa = ds(['ssn','fulladdress', 'date'], ['ssn', 'fulladdress'], 'ssnaddress_diff')
#day_sa = data_ref.groupby(['ssn','fulladdress', 'date'])['ssn', 'fulladdress', 'date'].first().groupby(['ssn', 'fulladdress']).diff()
#day_sa.columns = ['ssnaddress_diff']
#day_sa['ssnaddress_diff'] = day_sa['ssnaddress_diff'].dt.days.fillna(0)
#day_sa = day_sa.reset_index()

## phone + ssn
day_ps = ds(['homephone','ssn', 'date'], ['homephone', 'ssn'], 'phonessn_diff')
#day_ps = data_ref.groupby(['homephone','ssn', 'date'])['homephone', 'ssn', 'date'].first().groupby(['homephone', 'ssn']).diff()
#day_ps.columns = ['phonessn_diff']
#day_ps['phonessn_diff'] = day_ps['phonessn_diff'].dt.days.fillna(0)
#day_ps = day_ps.reset_index()

## phone + address
day_pa = ds(['homephone','fulladdress', 'date'], ['homephone', 'fulladdress'], 'phoneaddress_diff')
#day_pa = data_ref.groupby(['homephone','fulladdress', 'date'])['homephone', 'fulladdress', 'date'].first().groupby(['homephone', 'fulladdress']).diff()
#day_pa.columns = ['phoneaddress_diff']
#day_pa['phoneaddress_diff'] = day_pa['phoneaddress_diff'].dt.days.fillna(0)
#day_pa = day_pa.reset_index()

## ndop + phone
day_ndp = ds(['ndob','homephone', 'date'], ['ndob','homephone'], 'ndobphone_diff')
#day_ndp = data_ref.groupby(['ndob','homephone', 'date'])['ndob','homephone', 'date'].first().groupby(['ndob','homephone']).diff()
#day_ndp.columns = ['ndobphone_diff']
#day_ndp['ndobphone_diff'] = day_ndp['ndobphone_diff'].dt.days.fillna(0)
#day_ndp = day_ndp.reset_index()

## address + phone
day_ap = ds(['fulladdress','homephone', 'date'], ['fulladdress','homephone'], 'addressphone_diff')
#day_ap = data_ref.groupby(['fulladdress','homephone', 'date'])['fulladdress','homephone', 'date'].first().groupby(['fulladdress','homephone']).diff()
#day_ap.columns = ['addressphone_diff']
#day_ap['addressphone_diff'] = day_ap['addressphone_diff'].dt.days.fillna(0)
#day_ap = day_ap.reset_index()

## ndob + ssn
day_nds = ds(['ndob','ssn', 'date'], ['ndob', 'ssn'], 'ndobssn_diff')
#day_nds = data_ref.groupby(['ndob','ssn', 'date'])['ndob', 'ssn', 'date'].first().groupby(['ndob', 'ssn']).diff()
#day_nds.columns = ['ndobssn_diff']
#day_nds['ndobssn_diff'] = day_nds['ndobssn_diff'].dt.days.fillna(0)
#day_nds = day_nds.reset_index()

## ndob + address
day_nda = ds(['ndob','fulladdress', 'date'], ['ndob', 'fulladdress'], 'ndobaddress_diff')
#day_nda = data_ref.groupby(['ndob','fulladdress', 'date'])['ndob', 'fulladdress', 'date'].first().groupby(['ndob', 'fulladdress']).diff()
#day_nda.columns = ['ndobaddress_diff']
#day_nda['ndobaddress_diff'] = day_nda['ndobaddress_diff'].dt.days.fillna(0)
#day_nda = day_nda.reset_index()

## ssn + ndob
day_snd = ds(['ssn','ndob', 'date'], ['ssn', 'ndob'], 'ssnndob_diff')
# day_snd = data_ref.groupby(['ssn','ndob', 'date'])['ssn', 'ndob', 'date'].first().groupby(['ssn', 'ndob']).diff()
# day_snd.columns = ['ssnndob_diff']
# day_snd['ssnndob_diff'] = day_snd['ssnndob_diff'].dt.days.fillna(0)
# day_snd = day_snd.reset_index()

## fn + ssn
day_fns = ds(['firstname','ssn', 'date'], ['firstname', 'ssn'], 'fnssn_diff')
# day_fns = data_ref.groupby(['firstname','ssn', 'date'])['firstname', 'ssn', 'date'].first().groupby(['firstname', 'ssn']).diff()
# day_fns.columns = ['fnssn_diff']
# day_fns['fnssn_diff'] = day_fns['fnssn_diff'].dt.days.fillna(0)
# day_fns = day_fns.reset_index()

## ln + ssn
day_lns = ds(['lastname','ssn', 'date'], ['lastname','ssn'], 'lastnamessn_diff')
# day_lns = data_ref.groupby(['lastname','ssn', 'date'])['lastname','ssn', 'date'].first().groupby(['lastname','ssn']).diff()
# day_lns.columns = ['lastnamessn_diff']
# day_lns['lastnamessn_diff'] = day_lns['lastnamessn_diff'].dt.days.fillna(0)
# day_lns = day_lns.reset_index()

In [54]:
day_s.shape

(981139, 3)

In [55]:
day_s.head()

    ssn                          date  ssn_diff
0    36 1970-01-01 00:00:00.020160414       0.0
1    36 1970-01-01 00:00:00.020160613       0.0
2  2250 1970-01-01 00:00:00.020160130       0.0
3  2503 1970-01-01 00:00:00.020160810       0.0
4  2932 1970-01-01 00:00:00.020160413       0.0

In [56]:
day_a.shape

(996142, 3)

In [57]:
day_a.head()

        fulladdress                          date  address_diff
0   0 EAJA DR 51793 1970-01-01 00:00:00.020160405           0.0
1    0 EAJMZ ST 298 1970-01-01 00:00:00.020161023           0.0
2  0 EAUMS ST 78479 1970-01-01 00:00:00.020160211           0.0
3  0 EAURU WY 10803 1970-01-01 00:00:00.020160811           0.0
4  0 EAUSX LN 98300 1970-01-01 00:00:00.020160530           0.0

## Relative Velocity Variables

In [58]:
## ssn

freq_s = napps_s_1.merge(napps_s_3, how = 'inner', on = ['ssn', 'date', 'apps_by_s']).merge(napps_s_7, how = 'inner', on = ['ssn', 'date', 'apps_by_s']).merge(napps_s_14, how = 'inner', on = ['ssn', 'date', 'apps_by_s']).merge(napps_s_30, how = 'inner', on = ['ssn', 'date', 'apps_by_s'])

In [59]:
freq_s.shape

(1000000, 8)

In [60]:
freq_s.head(20)

,ssn,date,record_x,apps_by_s,record_y,record_x,record_y,record
0,36,1970-01-01 00:00:00.020160414,1.0,1,1.0,1.0,1.0,1.0
1,36,1970-01-01 00:00:00.020160613,2.0,1,2.0,2.0,2.0,2.0
2,2250,1970-01-01 00:00:00.020160130,1.0,1,1.0,1.0,1.0,1.0
3,2503,1970-01-01 00:00:00.020160810,1.0,1,1.0,1.0,1.0,1.0
4,2932,1970-01-01 00:00:00.020160413,1.0,1,1.0,1.0,1.0,1.0
5,5191,1970-01-01 00:00:00.020160926,1.0,1,1.0,1.0,1.0,1.0
6,6811,1970-01-01 00:00:00.020160315,1.0,1,1.0,1.0,1.0,1.0
7,7229,1970-01-01 00:00:00.020161116,1.0,1,1.0,1.0,1.0,1.0
8,8207,1970-01-01 00:00:00.020161024,1.0,1,1.0,1.0,1.0,1.0
9,8335,1970-01-01 00:00:00.020160519,1.0,1,1.0,1.0,1.0,1.0
10,9118,1970-01-01 00:00:00.020161224,1.0,1,1.0,1.0,1.0,1.0
11,9496,1970-01-01 00:00:00.020160826,1.0,1,1.0,1.0,1.0,1.0
12,10762,1970-01-01 00:00:00.020160224,1.0,1,1.0,1.0,1.0,1.0
13,11467,1970-01-01 00:00:00.020160611,1.0,1,1.0,1.0,1.0,1.0
14,14579,1970-01-01 00:00:00.020160101,1.0,1,1.0,1.0,1.0,1.0
15,16144,1970-01-01 00:00:00.020160126,1.0,1,1.0,1.0,1.0,1.0
16,16610,1970-01-01 00:00:00.020161109,1.0,1,1.0,1.0,1.0,1.0
17,17808,1970-01-01 00:00:00.020161028,1.0,1,1.0,1.0,1.0,1.0
18,18706,1970-01-01 00:00:00.020160310,1.0,1,1.0,1.0,1.0,1.0
19,20936,1970-01-01 00:00:00.020160812,1.0,1,1.0,1.0,1.0,1.0

In [61]:
freq_s.columns = ['ssn', 'date', 'napps_s_1', 'apps_by_s', 'napps_s_3', 'napps_s_7', 'napps_s_14', 'napps_s_30']
freq_s['v_ssn_3'] = freq_s['napps_s_1'] / freq_s['napps_s_3'] / 3
freq_s['v_ssn_7'] = freq_s['napps_s_1'] / freq_s['napps_s_7'] / 7
freq_s['v_ssn_14'] = freq_s['napps_s_1'] / freq_s['napps_s_14'] / 14
freq_s['v_ssn_30'] = freq_s['napps_s_1'] / freq_s['napps_s_30'] / 30

In [62]:
freq_s.head(40)

,ssn,date,napps_s_1,apps_by_s,napps_s_3,napps_s_7,napps_s_14,napps_s_30,v_ssn_3,v_ssn_7,v_ssn_14,v_ssn_30
0,36,1970-01-01 00:00:00.020160414,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
1,36,1970-01-01 00:00:00.020160613,2.0,1,2.0,2.0,2.0,2.0,0.333333,0.142857,0.071429,0.033333
2,2250,1970-01-01 00:00:00.020160130,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
3,2503,1970-01-01 00:00:00.020160810,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
4,2932,1970-01-01 00:00:00.020160413,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
5,5191,1970-01-01 00:00:00.020160926,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
6,6811,1970-01-01 00:00:00.020160315,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
7,7229,1970-01-01 00:00:00.020161116,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
8,8207,1970-01-01 00:00:00.020161024,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
9,8335,1970-01-01 00:00:00.020160519,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
10,9118,1970-01-01 00:00:00.020161224,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
11,9496,1970-01-01 00:00:00.020160826,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
12,10762,1970-01-01 00:00:00.020160224,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
13,11467,1970-01-01 00:00:00.020160611,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
14,14579,1970-01-01 00:00:00.020160101,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
15,16144,1970-01-01 00:00:00.020160126,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
16,16610,1970-01-01 00:00:00.020161109,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
17,17808,1970-01-01 00:00:00.020161028,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
18,18706,1970-01-01 00:00:00.020160310,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
19,20936,1970-01-01 00:00:00.020160812,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
20,23209,1970-01-01 00:00:00.020161020,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
21,24059,1970-01-01 00:00:00.020160519,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
22,28348,1970-01-01 00:00:00.020161123,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
23,30841,1970-01-01 00:00:00.020160520,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
24,31478,1970-01-01 00:00:00.020160611,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
25,33067,1970-01-01 00:00:00.020160310,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
26,33798,1970-01-01 00:00:00.020160403,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
27,35671,1970-01-01 00:00:00.020161225,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
28,37422,1970-01-01 00:00:00.020160111,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
29,37422,1970-01-01 00:00:00.020160520,2.0,1,2.0,2.0,2.0,2.0,0.333333,0.142857,0.071429,0.033333
30,37551,1970-01-01 00:00:00.020160107,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
31,38098,1970-01-01 00:00:00.020160505,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
32,39188,1970-01-01 00:00:00.020160817,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
33,40521,1970-01-01 00:00:00.020160625,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
34,40669,1970-01-01 00:00:00.020161013,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
35,40821,1970-01-01 00:00:00.020160611,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
36,40863,1970-01-01 00:00:00.020160818,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
37,40863,1970-01-01 00:00:00.020161127,2.0,1,2.0,2.0,2.0,2.0,0.333333,0.142857,0.071429,0.033333
38,41928,1970-01-01 00:00:00.020160412,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
39,44442,1970-01-01 00:00:00.020160903,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333

In [63]:
## address

freq_a = napps_a_1.merge(napps_a_3, how = 'inner', on = ['fulladdress', 'date', 'apps_by_a']).merge(napps_a_7, how = 'inner', on = ['fulladdress', 'date', 'apps_by_a']).merge(napps_a_14, how = 'inner', on = ['fulladdress', 'date', 'apps_by_a']).merge(napps_a_30, how = 'inner', on = ['fulladdress', 'date', 'apps_by_a'])
freq_a.columns = ['fulladdress', 'date', 'napps_a_1', 'apps_by_a', 'napps_a_3', 'napps_a_7', 'napps_a_14', 'napps_a_30']
freq_a['v_a_3'] = freq_a['napps_a_1'] / freq_a['napps_a_3'] / 3
freq_a['v_a_7'] = freq_a['napps_a_1'] / freq_a['napps_a_7'] / 7
freq_a['v_a_14'] = freq_a['napps_a_1'] / freq_a['napps_a_14'] / 14
freq_a['v_a_30'] = freq_a['napps_a_1'] / freq_a['napps_a_30'] / 30

In [64]:
## ndob

freq_ndob = napps_ndob_1.merge(napps_ndob_3, how = 'inner', on = ['ndob', 'date', 'apps_by_ndob']).merge(napps_ndob_7, how = 'inner', on = ['ndob', 'date', 'apps_by_ndob']).merge(napps_ndob_14, how = 'inner', on = ['ndob', 'date', 'apps_by_ndob']).merge(napps_ndob_30, how = 'inner', on = ['ndob', 'date', 'apps_by_ndob'])
freq_ndob.columns = ['ndob', 'date', 'napps_ndob_1', 'apps_by_ndob', 'napps_ndob_3', 'napps_ndob_7', 'napps_ndob_14', 'napps_ndob_30']
freq_ndob['v_ndob_3'] = freq_ndob['napps_ndob_1'] / freq_ndob['napps_ndob_3'] / 3
freq_ndob['v_ndob_7'] = freq_ndob['napps_ndob_1'] / freq_ndob['napps_ndob_7'] / 7
freq_ndob['v_ndob_14'] = freq_ndob['napps_ndob_1'] / freq_ndob['napps_ndob_14'] / 14
freq_ndob['v_ndob_30'] = freq_ndob['napps_ndob_1'] / freq_ndob['napps_ndob_30'] / 30

In [65]:
## phone

freq_p = napps_p_1.merge(napps_p_3, how = 'inner', on = ['homephone', 'date', 'apps_by_p']).merge(napps_p_7, how = 'inner', on = ['homephone', 'date', 'apps_by_p']).merge(napps_p_14, how = 'inner', on = ['homephone', 'date', 'apps_by_p']).merge(napps_p_30, how = 'inner', on = ['homephone', 'date', 'apps_by_p'])
freq_p.columns = ['homephone', 'date', 'napps_p_1', 'apps_by_p', 'napps_p_3', 'napps_p_7', 'napps_p_14', 'napps_p_30']
freq_p['v_p_3'] = freq_p['napps_p_1'] / freq_p['napps_p_3'] / 3
freq_p['v_p_7'] = freq_p['napps_p_1'] / freq_p['napps_p_7'] / 7
freq_p['v_p_14'] = freq_p['napps_p_1'] / freq_p['napps_p_14'] / 14
freq_p['v_p_30'] = freq_p['napps_p_1'] / freq_p['napps_p_30'] / 30

In [66]:
## sa

freq_sa = napps_sa_1.merge(napps_sa_3, how = 'inner', on = ['ssn', 'fulladdress', 'date', 'apps_by_sa']).merge(napps_sa_7, how = 'inner', on = ['ssn', 'fulladdress', 'date', 'apps_by_sa']).merge(napps_sa_14, how = 'inner', on = ['ssn', 'fulladdress', 'date', 'apps_by_sa']).merge(napps_sa_30, how = 'inner', on = ['ssn', 'fulladdress', 'date', 'apps_by_sa'])
freq_sa.columns = ['ssn', 'fulladdress', 'date', 'napps_sa_1', 'apps_by_sa', 'napps_sa_3', 'napps_sa_7', 'napps_sa_14', 'napps_sa_30']
freq_sa['v_sa_3'] = freq_sa['napps_sa_1'] / freq_sa['napps_sa_3'] / 3
freq_sa['v_sa_7'] = freq_sa['napps_sa_1'] / freq_sa['napps_sa_7'] / 7
freq_sa['v_sa_14'] = freq_sa['napps_sa_1'] / freq_sa['napps_sa_14'] / 14
freq_sa['v_sa_30'] = freq_sa['napps_sa_1'] / freq_sa['napps_sa_30'] / 30

In [67]:
freq_sa.shape

(1000000, 13)

In [68]:
freq_sa.head(20)

,ssn,fulladdress,date,napps_sa_1,apps_by_sa,napps_sa_3,napps_sa_7,napps_sa_14,napps_sa_30,v_sa_3,v_sa_7,v_sa_14,v_sa_30
0,36,9843 ARUA PL 71230,1970-01-01 00:00:00.020160414,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
1,36,9843 ARUA PL 71230,1970-01-01 00:00:00.020160613,2.0,1,2.0,2.0,2.0,2.0,0.333333,0.142857,0.071429,0.033333
2,2250,8450 ZXMJ WY 68456,1970-01-01 00:00:00.020160130,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
3,2503,1518 XZUEA PL 21505,1970-01-01 00:00:00.020160810,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
4,2932,7988 XSTUU WY 75404,1970-01-01 00:00:00.020160413,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
5,5191,9571 XASAE DR 29014,1970-01-01 00:00:00.020160926,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
6,6811,2596 SXEAT AVE 55737,1970-01-01 00:00:00.020160315,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
7,7229,4625 EMZZT BLVD 57492,1970-01-01 00:00:00.020161116,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
8,8207,6231 ETTR ST 47925,1970-01-01 00:00:00.020161024,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
9,8335,8688 XSXE CT 95964,1970-01-01 00:00:00.020160519,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
10,9118,1644 UTAMT ST 42406,1970-01-01 00:00:00.020161224,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
11,9496,601 RAAJX AVE 17324,1970-01-01 00:00:00.020160826,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
12,10762,3188 SMRRX AVE 29971,1970-01-01 00:00:00.020160224,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
13,11467,2786 TZAS WY 41130,1970-01-01 00:00:00.020160611,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
14,14579,8361 UEJ LN 81978,1970-01-01 00:00:00.020160101,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
15,16144,1724 SASTX LN 34712,1970-01-01 00:00:00.020160126,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
16,16610,680 XZTJX BLVD 6984,1970-01-01 00:00:00.020161109,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
17,17808,8914 USSTX PL 34875,1970-01-01 00:00:00.020161028,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
18,18706,5426 ERTME WY 40985,1970-01-01 00:00:00.020160310,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
19,20936,8443 RAMZ ST 61392,1970-01-01 00:00:00.020160812,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333

In [69]:
## ps

freq_ps = napps_ps_1.merge(napps_ps_3, how = 'inner', on = ['homephone', 'ssn', 'date', 'apps_by_ps']).merge(napps_ps_7, how = 'inner', on = ['homephone', 'ssn', 'date', 'apps_by_ps']).merge(napps_ps_14, how = 'inner', on = ['homephone', 'ssn', 'date', 'apps_by_ps']).merge(napps_ps_30, how = 'inner', on = ['homephone', 'ssn', 'date', 'apps_by_ps'])
freq_ps.columns = ['homephone', 'ssn', 'date', 'napps_ps_1', 'apps_by_ps', 'napps_ps_3', 'napps_ps_7', 'napps_ps_14', 'napps_ps_30']
freq_ps['v_ps_3'] = freq_ps['napps_ps_1'] / freq_ps['napps_ps_3'] / 3
freq_ps['v_ps_7'] = freq_ps['napps_ps_1'] / freq_ps['napps_ps_7'] / 7
freq_ps['v_ps_14'] = freq_ps['napps_ps_1'] / freq_ps['napps_ps_14'] / 14
freq_ps['v_ps_30'] = freq_ps['napps_ps_1'] / freq_ps['napps_ps_30'] / 30

In [70]:
## pa

freq_pa = napps_pa_1.merge(napps_pa_3, how = 'inner', on = ['homephone', 'fulladdress', 'date', 'apps_by_pa']).merge(napps_pa_7, how = 'inner', on = ['homephone', 'fulladdress', 'date', 'apps_by_pa']).merge(napps_pa_14, how = 'inner', on = ['homephone', 'fulladdress', 'date', 'apps_by_pa']).merge(napps_pa_30, how = 'inner', on = ['homephone', 'fulladdress', 'date', 'apps_by_pa'])
freq_pa.columns = ['homephone', 'fulladdress', 'date', 'napps_pa_1', 'apps_by_pa', 'napps_pa_3', 'napps_pa_7', 'napps_pa_14', 'napps_pa_30']
freq_pa['v_pa_3'] = freq_pa['napps_pa_1'] / freq_pa['napps_pa_3'] / 3
freq_pa['v_pa_7'] = freq_pa['napps_pa_1'] / freq_pa['napps_pa_7'] / 7
freq_pa['v_pa_14'] = freq_pa['napps_pa_1'] / freq_pa['napps_pa_14'] / 14
freq_pa['v_pa_30'] = freq_pa['napps_pa_1'] / freq_pa['napps_pa_30'] / 30

In [71]:
## ndp 

freq_ndp = napps_ndp_1.merge(napps_ndp_3, how = 'inner', on = ['ndob', 'homephone', 'date', 'apps_by_ndp']).merge(napps_ndp_7, how = 'inner', on = ['ndob', 'homephone', 'date', 'apps_by_ndp']).merge(napps_ndp_14, how = 'inner', on = ['ndob', 'homephone', 'date', 'apps_by_ndp']).merge(napps_ndp_30, how = 'inner', on = ['ndob', 'homephone', 'date', 'apps_by_ndp'])
freq_ndp.columns = ['ndob', 'homephone', 'date', 'napps_ndp_1', 'apps_by_ndp', 'napps_ndp_3', 'napps_ndp_7', 'napps_ndp_14', 'napps_ndp_30']
freq_ndp['v_ndp_3'] = freq_ndp['napps_ndp_1'] / freq_ndp['napps_ndp_3'] / 3
freq_ndp['v_ndp_7'] = freq_ndp['napps_ndp_1'] / freq_ndp['napps_ndp_7'] / 7
freq_ndp['v_ndp_14'] = freq_ndp['napps_ndp_1'] / freq_ndp['napps_ndp_14'] / 14
freq_ndp['v_ndp_30'] = freq_ndp['napps_ndp_1'] / freq_ndp['napps_ndp_30'] / 30

In [72]:
## ap

freq_ap = napps_ap_1.merge(napps_ap_3, how = 'inner', on = ['fulladdress', 'homephone', 'date', 'apps_by_ap']).merge(napps_ap_7, how = 'inner', on = ['fulladdress', 'homephone', 'date', 'apps_by_ap']).merge(napps_ap_14, how = 'inner', on = ['fulladdress', 'homephone', 'date', 'apps_by_ap']).merge(napps_ap_30, how = 'inner', on = ['fulladdress', 'homephone', 'date', 'apps_by_ap'])
freq_ap.columns = ['fulladdress', 'homephone', 'date', 'napps_ap_1', 'apps_by_ap', 'napps_ap_3', 'napps_ap_7', 'napps_ap_14', 'napps_ap_30']
freq_ap['v_ap_3'] = freq_ap['napps_ap_1'] / freq_ap['napps_ap_3'] / 3
freq_ap['v_ap_7'] = freq_ap['napps_ap_1'] / freq_ap['napps_ap_7'] / 7
freq_ap['v_ap_14'] = freq_ap['napps_ap_1'] / freq_ap['napps_ap_14'] / 14
freq_ap['v_ap_30'] = freq_ap['napps_ap_1'] / freq_ap['napps_ap_30'] / 30

In [73]:
## nds

freq_nds = napps_nds_1.merge(napps_nds_3, how = 'inner', on = ['ndob', 'ssn', 'date', 'apps_by_nds']).merge(napps_nds_7, how = 'inner', on = ['ndob', 'ssn', 'date', 'apps_by_nds']).merge(napps_nds_14, how = 'inner', on = ['ndob', 'ssn', 'date', 'apps_by_nds']).merge(napps_nds_30, how = 'inner', on = ['ndob', 'ssn', 'date', 'apps_by_nds'])
freq_nds.columns = ['ndob', 'ssn', 'date', 'napps_nds_1', 'apps_by_nds', 'napps_nds_3', 'napps_nds_7', 'napps_nds_14', 'napps_nds_30']
freq_nds['v_nds_3'] = freq_nds['napps_nds_1'] / freq_nds['napps_nds_3'] / 3
freq_nds['v_nds_7'] = freq_nds['napps_nds_1'] / freq_nds['napps_nds_7'] / 7
freq_nds['v_nds_14'] = freq_nds['napps_nds_1'] / freq_nds['napps_nds_14'] / 14
freq_nds['v_nds_30'] = freq_nds['napps_nds_1'] / freq_nds['napps_nds_30'] / 30

In [74]:
## nda

freq_nda = napps_nda_1.merge(napps_nda_3, how = 'inner', on = ['ndob', 'fulladdress', 'date', 'apps_by_nda']).merge(napps_nda_7, how = 'inner', on = ['ndob', 'fulladdress', 'date', 'apps_by_nda']).merge(napps_nda_14, how = 'inner', on = ['ndob', 'fulladdress', 'date', 'apps_by_nda']).merge(napps_nda_30, how = 'inner', on = ['ndob', 'fulladdress', 'date', 'apps_by_nda'])
freq_nda.columns = ['ndob', 'fulladdress', 'date', 'napps_nda_1', 'apps_by_nda', 'napps_nda_3', 'napps_nda_7', 'napps_nda_14', 'napps_nda_30']
freq_nda['v_nda_3'] = freq_nda['napps_nda_1'] / freq_nda['napps_nda_3'] / 3
freq_nda['v_nda_7'] = freq_nda['napps_nda_1'] / freq_nda['napps_nda_7'] / 7
freq_nda['v_nda_14'] = freq_nda['napps_nda_1'] / freq_nda['napps_nda_14'] / 14
freq_nda['v_nda_30'] = freq_nda['napps_nda_1'] / freq_nda['napps_nda_30'] / 30

In [75]:
## snd

freq_snd = napps_snd_1.merge(napps_snd_3, how = 'inner', on = ['ssn', 'ndob', 'date', 'apps_by_snd']).merge(napps_snd_7, how = 'inner', on = ['ssn', 'ndob', 'date', 'apps_by_snd']).merge(napps_snd_14, how = 'inner', on = ['ssn', 'ndob', 'date', 'apps_by_snd']).merge(napps_snd_30, how = 'inner', on = ['ssn', 'ndob', 'date', 'apps_by_snd'])
freq_snd.columns = ['ssn', 'ndob', 'date', 'napps_snd_1', 'apps_by_snd', 'napps_snd_3', 'napps_snd_7', 'napps_snd_14', 'napps_snd_30']
freq_snd['v_snd_3'] = freq_snd['napps_snd_1'] / freq_snd['napps_snd_3'] / 3
freq_snd['v_snd_7'] = freq_snd['napps_snd_1'] / freq_snd['napps_snd_7'] / 7
freq_snd['v_snd_14'] = freq_snd['napps_snd_1'] / freq_snd['napps_snd_14'] / 14
freq_snd['v_snd_30'] = freq_snd['napps_snd_1'] / freq_snd['napps_snd_30'] / 30

In [76]:
## fns

freq_fns = napps_fns_1.merge(napps_fns_3, how = 'inner', on = ['firstname', 'ssn', 'date', 'apps_by_fns']).merge(napps_fns_7, how = 'inner', on = ['firstname', 'ssn', 'date', 'apps_by_fns']).merge(napps_fns_14, how = 'inner', on = ['firstname', 'ssn', 'date', 'apps_by_fns']).merge(napps_fns_30, how = 'inner', on = ['firstname', 'ssn', 'date', 'apps_by_fns'])
freq_fns.columns = ['firstname', 'ssn', 'date', 'napps_fns_1', 'apps_by_fns', 'napps_fns_3', 'napps_fns_7', 'napps_fns_14', 'napps_fns_30']
freq_fns['v_fns_3'] = freq_fns['napps_fns_1'] / freq_fns['napps_fns_3'] / 3
freq_fns['v_fns_7'] = freq_fns['napps_fns_1'] / freq_fns['napps_fns_7'] / 7
freq_fns['v_fns_14'] = freq_fns['napps_fns_1'] / freq_fns['napps_fns_14'] / 14
freq_fns['v_fns_30'] = freq_fns['napps_fns_1'] / freq_fns['napps_fns_30'] / 30

In [77]:
## lns

freq_lns = napps_lns_1.merge(napps_lns_3, how = 'inner', on = ['lastname', 'ssn', 'date', 'apps_by_lns']).merge(napps_lns_7, how = 'inner', on = ['lastname', 'ssn', 'date', 'apps_by_lns']).merge(napps_lns_14, how = 'inner', on = ['lastname', 'ssn', 'date', 'apps_by_lns']).merge(napps_lns_30, how = 'inner', on = ['lastname', 'ssn', 'date', 'apps_by_lns'])
freq_lns.columns = ['lastname', 'ssn', 'date', 'napps_lns_1', 'apps_by_lns', 'napps_lns_3', 'napps_lns_7', 'napps_lns_14', 'napps_lns_30']
freq_lns['v_lns_3'] = freq_lns['napps_lns_1'] / freq_lns['napps_lns_3'] / 3
freq_lns['v_lns_7'] = freq_lns['napps_lns_1'] / freq_lns['napps_lns_7'] / 7
freq_lns['v_lns_14'] = freq_lns['napps_lns_1'] / freq_lns['napps_lns_14'] / 14
freq_lns['v_lns_30'] = freq_lns['napps_lns_1'] / freq_lns['napps_lns_30'] / 30

In [78]:
freq_s.head(40)

,ssn,date,napps_s_1,apps_by_s,napps_s_3,napps_s_7,napps_s_14,napps_s_30,v_ssn_3,v_ssn_7,v_ssn_14,v_ssn_30
0,36,1970-01-01 00:00:00.020160414,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
1,36,1970-01-01 00:00:00.020160613,2.0,1,2.0,2.0,2.0,2.0,0.333333,0.142857,0.071429,0.033333
2,2250,1970-01-01 00:00:00.020160130,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
3,2503,1970-01-01 00:00:00.020160810,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
4,2932,1970-01-01 00:00:00.020160413,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
5,5191,1970-01-01 00:00:00.020160926,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
6,6811,1970-01-01 00:00:00.020160315,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
7,7229,1970-01-01 00:00:00.020161116,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
8,8207,1970-01-01 00:00:00.020161024,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
9,8335,1970-01-01 00:00:00.020160519,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
10,9118,1970-01-01 00:00:00.020161224,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
11,9496,1970-01-01 00:00:00.020160826,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
12,10762,1970-01-01 00:00:00.020160224,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
13,11467,1970-01-01 00:00:00.020160611,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
14,14579,1970-01-01 00:00:00.020160101,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
15,16144,1970-01-01 00:00:00.020160126,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
16,16610,1970-01-01 00:00:00.020161109,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
17,17808,1970-01-01 00:00:00.020161028,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
18,18706,1970-01-01 00:00:00.020160310,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
19,20936,1970-01-01 00:00:00.020160812,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
20,23209,1970-01-01 00:00:00.020161020,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
21,24059,1970-01-01 00:00:00.020160519,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
22,28348,1970-01-01 00:00:00.020161123,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
23,30841,1970-01-01 00:00:00.020160520,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
24,31478,1970-01-01 00:00:00.020160611,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
25,33067,1970-01-01 00:00:00.020160310,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
26,33798,1970-01-01 00:00:00.020160403,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
27,35671,1970-01-01 00:00:00.020161225,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
28,37422,1970-01-01 00:00:00.020160111,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
29,37422,1970-01-01 00:00:00.020160520,2.0,1,2.0,2.0,2.0,2.0,0.333333,0.142857,0.071429,0.033333
30,37551,1970-01-01 00:00:00.020160107,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
31,38098,1970-01-01 00:00:00.020160505,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
32,39188,1970-01-01 00:00:00.020160817,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
33,40521,1970-01-01 00:00:00.020160625,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
34,40669,1970-01-01 00:00:00.020161013,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
35,40821,1970-01-01 00:00:00.020160611,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
36,40863,1970-01-01 00:00:00.020160818,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
37,40863,1970-01-01 00:00:00.020161127,2.0,1,2.0,2.0,2.0,2.0,0.333333,0.142857,0.071429,0.033333
38,41928,1970-01-01 00:00:00.020160412,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333
39,44442,1970-01-01 00:00:00.020160903,1.0,1,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333

In [79]:
data_orig.head(40)

,record,date,ssn,firstname,lastname,dob,homephone,fraud_label,fulladdress,ndob
0,1,1970-01-01 00:00:00.020160101,379070012,XRRAMMTR,SMJETJMJ,19070626,1797504115,0,6861 EUTST PL 2765,XRRAMMTRSMJETJMJ19070626
1,2,1970-01-01 00:00:00.020160101,387482503,MAMSTUJR,RTTEMRRR,19340615,4164239415,1,7280 URASA PL 57169,MAMSTUJRRTTEMRRR19340615
2,3,1970-01-01 00:00:00.020160101,200332444,SZMMUJEZS,EUSEZRAE,19070626,216537580,0,5581 RSREX LN 56721,SZMMUJEZSEUSEZRAE19070626
3,4,1970-01-01 00:00:00.020160101,747451317,SJJZSXRSZ,ETJXTXXS,19440430,132144161,0,1387 UJZXJ RD 35286,SJJZSXRSZETJXTXXS19440430
4,5,1970-01-01 00:00:00.020160101,24065868,SSSXUEJMS,SSUUJXUZ,19980315,6101082272,0,279 EAASA WY 3173,SSSXUEJMSSSUUJXUZ19980315
5,6,1970-01-01 00:00:00.020160101,922264214,XEEJJSTER,ERJSAXA,19480613,5742016319,0,4322 USJXU LN 8391,XEEJJSTERERJSAXA19480613
6,7,1970-01-01 00:00:00.020160101,415812149,XZJRJUSRR,STSMJRUM,19640318,7697396312,0,478 EEXUM LN 41640,XZJRJUSRRSTSMJRUM19640318
7,8,1970-01-01 00:00:00.020160101,373752050,EJMRRSUXR,AMTZXRU,19190528,2727421586,0,8906 UUAJ PL 60567,EJMRRSUXRAMTZXRU19190528
8,9,1970-01-01 00:00:00.020160101,769970791,RXTSZJATS,RSXMRJME,19900314,5520652307,0,8266 SSEAR RD 37934,RXTSZJATSRSXMRJME19900314
9,10,1970-01-01 00:00:00.020160101,732119085,EREMTZXXA,EXMMSEXT,19750127,3749451123,0,9166 XXSAZ PL 93751,EREMTZXXAEXMMSEXT19750127
10,11,1970-01-01 00:00:00.020160101,999999999,UZZSMXSEE,USJZUSA,19400126,3026547212,0,726 UMTXU ST 92129,UZZSMXSEEUSJZUSA19400126
11,12,1970-01-01 00:00:00.020160101,854773981,RSZXMZRSU,EZJAXJTZ,19471211,3896260651,0,2561 RXJXU BLVD 9531,RSZXMZRSUEZJAXJTZ19471211
12,13,1970-01-01 00:00:00.020160101,283419783,EJAASJXXM,UZZSAZJR,19000122,5874359299,0,4365 UMXZA LN 82369,EJAASJXXMUZZSAZJR19000122
13,14,1970-01-01 00:00:00.020160101,800705980,MUTAEUUZS,STAZJXRA,19400902,3903104222,0,1683 RSEJM ST 66204,MUTAEUUZSSTAZJXRA19400902
14,15,1970-01-01 00:00:00.020160101,654640127,SUXZRSUZT,UAJRRXM,19360829,1754954648,0,4961 RTZJA BLVD 61344,SUXZRSUZTUAJRRXM19360829
15,16,1970-01-01 00:00:00.020160101,763049287,XAREMEUUU,SXXJSARX,19991228,3915611901,0,6575 EXZXA RD 43912,XAREMEUUUSXXJSARX19991228
16,17,1970-01-01 00:00:00.020160101,610654961,UJSRSMUEZ,SJATAXXX,20080401,516200670,0,4057 SRZAE BLVD 29576,UJSRSMUEZSJATAXXX20080401
17,18,1970-01-01 00:00:00.020160101,346374636,XRSSZZUXT,ETXZXJAJ,19500110,9999999999,0,5719 UEZJT PL 51486,XRSSZZUXTETXZXJAJ19500110
18,19,1970-01-01 00:00:00.020160101,722620451,UXJSUXJUJ,UUMRUSA,19901113,439009868,0,1198 XAZZR PL 93301,UXJSUXJUJUUMRUSA19901113
19,20,1970-01-01 00:00:00.020160101,892971652,XUTMSSREZ,UJEUUJXT,20060815,1938458945,0,2350 EZTXX AVE 25166,XUTMSSREZUJEUUJXT20060815
20,21,1970-01-01 00:00:00.020160101,344025146,SJAXEZAMT,MERAUUU,19770328,6547182278,0,3142 MZZE WY 14589,SJAXEZAMTMERAUUU19770328
21,22,1970-01-01 00:00:00.020160101,624412170,RAJSJZUSZ,SSSEARET,19870706,6485706942,0,3775 RUXE DR 21860,RAJSJZUSZSSSEARET19870706
22,23,1970-01-01 00:00:00.020160101,999999999,ETXMUSZEM,UJMAMEU,19580830,5568704443,0,3387 STRUM WY 45982,ETXMUSZEMUJMAMEU19580830
23,24,1970-01-01 00:00:00.020160101,240172205,RRSAZXXEJ,ESSJAZMA,19770518,764218629,0,8715 STRJX ST 94373,RRSAZXXEJESSJAZMA19770518
24,25,1970-01-01 00:00:00.020160101,425320780,SREZUJMJU,RXRRRTMX,19381224,9070020107,0,626 STSRR ST 59453,SREZUJMJURXRRRTMX19381224
25,26,1970-01-01 00:00:00.020160101,726871640,XMTJTUSXM,EMMMTAAE,19690521,3020180571,0,2585 ERUZR LN 83363,XMTJTUSXMEMMMTAAE19690521
26,27,1970-01-01 00:00:00.020160101,735495403,EMSSTSXUA,STZRUXZM,19881111,9999999999,0,9323 STRMS PL 51395,EMSSTSXUASTZRUXZM19881111
27,28,1970-01-01 00:00:00.020160101,572953147,TXMZSZUE,XUJESAA,19151119,2019407715,0,105 RJAZM BLVD 93806,TXMZSZUEXUJESAA19151119
28,29,1970-01-01 00:00:00.020160101,702069537,SSZREMAMU,SXEJRUJJ,19890613,5814569297,0,6591 UAXSU RD 21920,SSZREMAMUSXEJRUJJ19890613
29,30,1970-01-01 00:00:00.020160101,811559368,RATZJTJJX,ETASRZEE,19070626,2498035994,0,1815 EJZJR BLVD 2214,RATZJTJJXETASRZEE19070626
30,31,1970-01-01 00:00:00.020160101,913950051,RMXXZTXTX,SXEJJMMX,19410726,7831679991,0,9943 SMTRM LN 78462,RMXXZTXTXSXEJJMMX19410726
31,32,1970-01-01 00:00:00.020160101,74493692,EAMSTRMT,USJZAESU,19980529,5887359448,0,4279 RMXEZ WY 44582,EAMSTRMTUSJZAESU19980529
32,33,1970-01-01 00:00:00.020160101,101770709,URMSTMRRM,UJESUAMT,19331228,6000374014,0,8045 RRJZE RD 55177,URMSTMRRMUJESUAMT19331228
33,34,1970-01-01 00:00:00.020160101,267778370,MUEZXXMEA,SSSJAZSR,19850213,2425504233,0,1277 TJRJ BLVD 58946,MUEZXXMEASSSJAZSR19850213
34,35,1970-01-01 00:00:00.020160101,839962578,XTSTSTRXZ,ERMJRETX,19310707,6812691716,0,6986 XZAST LN 91035,XTSTSTRXZERMJRETX19310707
35,36,1970-01-01 00:00:00.020160101,688281956,RTMTEEUTX,USMSTXUX,19610413,5790482182,0,3747 SSJEU ST 51708,RTMTEEUTXUSMSTXUX19610413
36,37,1970-01-01 00:00:00.020160101,361467082,UTEZXSMTE,EARSXARZ,19200606,8194796,0,6294 EXUJX LN 76025,UTEZXSMTEEARSXARZ19200606
37,38,1970-01-01 00:00:00.020160101,922903262,RSXTZRTS,URMXTTZM,19930826,2617083010,0,5091 EMZXX DR 10140,RSXTZRTSURMXTTZM19930826
38,39,1970-01-01 00:00:00.020160101,314366906,USTAZSZMT,ESMMSMZU,19450915,7141836414,0,177 SJXME RD 39713,USTAZSZMTESMMSMZU19450915
39,40,1970-01-01 00:00:00.020160101,565513146,UXXJJZTUZ,RASUSTES,19080303,6905546436,0,4846 XTUZT AVE 35809,UXXJJZTUZRASUSTES19080303

In [80]:
data.head(40)

,record,date,ssn,firstname,lastname,dob,homephone,fraud_label,fulladdress,ndob,...,apps_by_sa,apps_by_nda,apps_by_pa,apps_by_ndp,apps_by_ap,apps_by_ps,apps_by_nds,apps_by_snd,apps_by_fns,apps_by_lns
0,1,1970-01-01 00:00:00.020160101,379070012,XRRAMMTR,SMJETJMJ,19070626,1797504115,0,6861 EUTST PL 2765,XRRAMMTRSMJETJMJ19070626,...,1,1,1,1,1,1,1,1,1,1
1,2,1970-01-01 00:00:00.020160101,387482503,MAMSTUJR,RTTEMRRR,19340615,4164239415,1,7280 URASA PL 57169,MAMSTUJRRTTEMRRR19340615,...,1,1,1,1,1,1,1,1,1,1
2,3,1970-01-01 00:00:00.020160101,200332444,SZMMUJEZS,EUSEZRAE,19070626,216537580,0,5581 RSREX LN 56721,SZMMUJEZSEUSEZRAE19070626,...,1,1,1,1,1,1,1,1,1,1
3,4,1970-01-01 00:00:00.020160101,747451317,SJJZSXRSZ,ETJXTXXS,19440430,132144161,0,1387 UJZXJ RD 35286,SJJZSXRSZETJXTXXS19440430,...,1,1,1,1,1,1,1,1,1,1
4,5,1970-01-01 00:00:00.020160101,24065868,SSSXUEJMS,SSUUJXUZ,19980315,6101082272,0,279 EAASA WY 3173,SSSXUEJMSSSUUJXUZ19980315,...,1,1,1,1,1,1,1,1,1,1
5,6,1970-01-01 00:00:00.020160101,922264214,XEEJJSTER,ERJSAXA,19480613,5742016319,0,4322 USJXU LN 8391,XEEJJSTERERJSAXA19480613,...,1,1,1,1,1,1,1,1,1,1
6,7,1970-01-01 00:00:00.020160101,415812149,XZJRJUSRR,STSMJRUM,19640318,7697396312,0,478 EEXUM LN 41640,XZJRJUSRRSTSMJRUM19640318,...,1,1,1,1,1,1,1,1,1,1
7,8,1970-01-01 00:00:00.020160101,373752050,EJMRRSUXR,AMTZXRU,19190528,2727421586,0,8906 UUAJ PL 60567,EJMRRSUXRAMTZXRU19190528,...,1,1,1,1,1,1,1,1,1,1
8,9,1970-01-01 00:00:00.020160101,769970791,RXTSZJATS,RSXMRJME,19900314,5520652307,0,8266 SSEAR RD 37934,RXTSZJATSRSXMRJME19900314,...,1,1,1,1,1,1,1,1,1,1
9,10,1970-01-01 00:00:00.020160101,732119085,EREMTZXXA,EXMMSEXT,19750127,3749451123,0,9166 XXSAZ PL 93751,EREMTZXXAEXMMSEXT19750127,...,1,1,1,1,1,1,1,1,1,1
10,11,1970-01-01 00:00:00.020160101,999999999,UZZSMXSEE,USJZUSA,19400126,3026547212,0,726 UMTXU ST 92129,UZZSMXSEEUSJZUSA19400126,...,1,1,1,1,1,1,1,1,1,1
11,12,1970-01-01 00:00:00.020160101,854773981,RSZXMZRSU,EZJAXJTZ,19471211,3896260651,0,2561 RXJXU BLVD 9531,RSZXMZRSUEZJAXJTZ19471211,...,1,1,1,1,1,1,1,1,1,1
12,13,1970-01-01 00:00:00.020160101,283419783,EJAASJXXM,UZZSAZJR,19000122,5874359299,0,4365 UMXZA LN 82369,EJAASJXXMUZZSAZJR19000122,...,1,1,1,1,1,1,1,1,1,1
13,14,1970-01-01 00:00:00.020160101,800705980,MUTAEUUZS,STAZJXRA,19400902,3903104222,0,1683 RSEJM ST 66204,MUTAEUUZSSTAZJXRA19400902,...,1,1,1,1,1,1,1,1,1,1
14,15,1970-01-01 00:00:00.020160101,654640127,SUXZRSUZT,UAJRRXM,19360829,1754954648,0,4961 RTZJA BLVD 61344,SUXZRSUZTUAJRRXM19360829,...,1,1,1,1,1,1,1,1,1,1
15,16,1970-01-01 00:00:00.020160101,763049287,XAREMEUUU,SXXJSARX,19991228,3915611901,0,6575 EXZXA RD 43912,XAREMEUUUSXXJSARX19991228,...,1,1,1,1,1,1,1,1,1,1
16,17,1970-01-01 00:00:00.020160101,610654961,UJSRSMUEZ,SJATAXXX,20080401,516200670,0,4057 SRZAE BLVD 29576,UJSRSMUEZSJATAXXX20080401,...,1,1,1,1,1,1,1,1,1,1
17,18,1970-01-01 00:00:00.020160101,346374636,XRSSZZUXT,ETXZXJAJ,19500110,9999999999,0,5719 UEZJT PL 51486,XRSSZZUXTETXZXJAJ19500110,...,1,1,1,1,1,1,1,1,1,1
18,19,1970-01-01 00:00:00.020160101,722620451,UXJSUXJUJ,UUMRUSA,19901113,439009868,0,1198 XAZZR PL 93301,UXJSUXJUJUUMRUSA19901113,...,1,1,1,1,1,1,1,1,1,1
19,20,1970-01-01 00:00:00.020160101,892971652,XUTMSSREZ,UJEUUJXT,20060815,1938458945,0,2350 EZTXX AVE 25166,XUTMSSREZUJEUUJXT20060815,...,1,1,1,1,1,1,1,1,1,1
20,21,1970-01-01 00:00:00.020160101,344025146,SJAXEZAMT,MERAUUU,19770328,6547182278,0,3142 MZZE WY 14589,SJAXEZAMTMERAUUU19770328,...,1,1,1,1,1,1,1,1,1,1
21,22,1970-01-01 00:00:00.020160101,624412170,RAJSJZUSZ,SSSEARET,19870706,6485706942,0,3775 RUXE DR 21860,RAJSJZUSZSSSEARET19870706,...,1,1,1,1,1,1,1,1,1,1
22,23,1970-01-01 00:00:00.020160101,999999999,ETXMUSZEM,UJMAMEU,19580830,5568704443,0,3387 STRUM WY 45982,ETXMUSZEMUJMAMEU19580830,...,1,1,1,1,1,1,1,1,1,1
23,24,1970-01-01 00:00:00.020160101,240172205,RRSAZXXEJ,ESSJAZMA,19770518,764218629,0,8715 STRJX ST 94373,RRSAZXXEJESSJAZMA19770518,...,1,1,1,1,1,1,1,1,1,1
24,25,1970-01-01 00:00:00.020160101,425320780,SREZUJMJU,RXRRRTMX,19381224,9070020107,0,626 STSRR ST 59453,SREZUJMJURXRRRTMX19381224,...,1,1,1,1,1,1,1,1,1,1
25,26,1970-01-01 00:00:00.020160101,726871640,XMTJTUSXM,EMMMTAAE,19690521,3020180571,0,2585 ERUZR LN 83363,XMTJTUSXMEMMMTAAE19690521,...,1,1,1,1,1,1,1,1,1,1
26,27,1970-01-01 00:00:00.020160101,735495403,EMSSTSXUA,STZRUXZM,19881111,9999999999,0,9323 STRMS PL 51395,EMSSTSXUASTZRUXZM19881111,...,1,1,1,1,1,1,1,1,1,1
27,28,1970-01-01 00:00:00.020160101,572953147,TXMZSZUE,XUJESAA,19151119,2019407715,0,105 RJAZM BLVD 93806,TXMZSZUEXUJESAA19151119,...,1,1,1,1,1,1,1,1,1,1
28,29,1970-01-01 00:00:00.020160101,702069537,SSZREMAMU,SXEJRUJJ,19890613,5814569297,0,6591 UAXSU RD 21920,SSZREMAMUSXEJRUJJ19890613,...,1,1,1,1,1,1,1,1,1,1
29,30,1970-01-01 00:00:00.020160101,811559368,RATZJTJJX,ETASRZEE,19070626,2498035994,0,1815 EJZJR BLVD 2214,RATZJTJJXETASRZEE19070626,...,1,1,1,1,1,1,1,1,1,1
30,31,1970-01-01 00:00:00.020160101,913950051,RMXXZTXTX,SXEJJMMX,19410726,7831679991,0,9943 SMTRM LN 78462,RMXXZTXTXSXEJJMMX19410726,...,1,1,1,1,1,1,1,1,1,1
31,32,1970-01-01 00:00:00.020160101,74493692,EAMSTRMT,USJZAESU,19980529,5887359448,0,4279 RMXEZ WY 44582,EAMSTRMTUSJZAESU19980529,...,1,1,1,1,1,1,1,1,1,1
32,33,1970-01-01 00:00:00.020160101,101770709,URMSTMRRM,UJESUAMT,19331228,6000374014,0,8045 RRJZE RD 55177,URMSTMRRMUJESUAMT19331228,...,1,1,1,1,1,1,1,1,1,1
33,34,1970-01-01 00:00:00.020160101,267778370,MUEZXXMEA,SSSJAZSR,19850213,2425504233,0,1277 TJRJ BLVD 58946,MUEZXXMEASSSJAZSR19850213,...,1,1,1,1,1,1,1,1,1,1
34,35,1970-01-01 00:00:00.020160101,839962578,XTSTSTRXZ,ERMJRETX,19310707,6812691716,0,6986 XZAST LN 91035,XTSTSTRXZERMJRETX19310707,...,1,1,1,1,1,1,1,1,1,1
35,36,1970-01-01 00:00:00.020160101,688281956,RTMTEEUTX,USMSTXUX,19610413,5790482182,0,3747 SSJEU ST 51708,RTMTEEUTXUSMSTXUX19610413,...,1,1,1,1,1,1,1,1,1,1
36,37,1970-01-01 00:00:00.020160101,361467082,UTEZXSMTE,EARSXARZ,19200606,8194796,0,6294 EXUJX LN 76025,UTEZXSMTEEARSXARZ19200606,...,1,1,1,1,1,1,1,1,1,1
37,38,1970-01-01 00:00:00.020160101,922903262,RSXTZRTS,URMXTTZM,19930826,2617083010,0,5091 EMZXX DR 10140,RSXTZRTSURMXTTZM19930826,...,1,1,1,1,1,1,1,1,1,1
38,39,1970-01-01 00:00:00.020160101,314366906,USTAZSZMT,ESMMSMZU,19450915,7141836414,0,177 SJXME RD 39713,USTAZSZMTESMMSMZU19450915,...,1,1,1,1,1,1,1,1,1,1
39,40,1970-01-01 00:00:00.020160101,565513146,UXXJJZTUZ,RASUSTES,19080303,6905546436,0,4846 XTUZT AVE 35809,UXXJJZTUZRASUSTES19080303,...,1,1,1,1,1,1,1,1,1,1

In [81]:
# all_vars = data_orig.merge(freq_ssn.merge(day_ssn, how = 'inner', on = ['ssn', 'date']))
# all_vars = data.merge(freq_ssn, how = 'inner', on = ['ssn', 'date', 'apps_by_s']).merge(day_ssn, how = 'inner', on = ['ssn', 'date'])

In [82]:
# all_vars.head(40)

## Combine Variables

In [83]:
vars_s = data.merge(freq_s, how = 'inner', on = ['ssn', 'date', 'apps_by_s']).merge(day_s, how = 'inner', on = ['ssn', 'date'])
vars_a = data.merge(freq_a, how = 'inner', on = ['fulladdress', 'date', 'apps_by_a']).merge(day_a, how = 'inner', on = ['fulladdress', 'date'])
vars_ndob = data.merge(freq_ndob, how = 'inner', on = ['ndob', 'date', 'apps_by_ndob']).merge(day_ndob, how = 'inner', on = ['ndob', 'date'])
vars_p = data.merge(freq_p, how = 'inner', on = ['homephone', 'date', 'apps_by_p']).merge(day_p, how = 'inner', on = ['homephone', 'date'])
vars_sa = data.merge(freq_sa, how = 'inner', on = ['ssn', 'fulladdress', 'date', 'apps_by_sa']).merge(day_sa, how = 'inner', on = ['ssn', 'fulladdress', 'date'])
vars_nda = data.merge(freq_nda, how = 'inner', on = ['ndob', 'fulladdress', 'date', 'apps_by_nda']).merge(day_nda, how = 'inner', on = ['ndob', 'fulladdress', 'date'])
vars_pa = data.merge(freq_pa, how = 'inner', on = ['homephone', 'fulladdress', 'date', 'apps_by_pa']).merge(day_pa, how = 'inner', on = ['homephone','fulladdress', 'date'])
vars_ndp = data.merge(freq_ndp, how = 'inner', on = ['ndob', 'homephone', 'date', 'apps_by_ndp']).merge(day_ndp, how = 'inner', on = ['ndob', 'homephone', 'date'])
vars_ap = data.merge(freq_ap, how = 'inner', on = ['fulladdress', 'homephone', 'date', 'apps_by_ap']).merge(day_ap, how = 'inner', on = ['fulladdress', 'homephone', 'date'])
vars_ps = data.merge(freq_ps, how = 'inner', on = ['homephone', 'ssn', 'date', 'apps_by_ps']).merge(day_ps, how = 'inner', on = ['homephone', 'ssn', 'date'])
vars_nds = data.merge(freq_nds, how = 'inner', on = ['ndob', 'ssn', 'date', 'apps_by_nds']).merge(day_nds, how = 'inner', on = ['ndob', 'ssn', 'date'])
vars_snd = data.merge(freq_snd, how = 'inner', on = ['ssn', 'ndob', 'date', 'apps_by_snd']).merge(day_snd, how = 'inner', on = ['ssn','ndob', 'date'])
vars_fns = data.merge(freq_fns, how = 'inner', on = ['firstname', 'ssn', 'date', 'apps_by_fns']).merge(day_fns, how = 'inner', on = ['firstname','ssn', 'date'])
vars_lns = data.merge(freq_lns, how = 'inner', on = ['lastname', 'ssn', 'date', 'apps_by_lns']).merge(day_lns, how = 'inner', on = ['lastname', 'ssn', 'date'])

In [84]:
# vars_ssn.head(20)

In [85]:
vars_sa.head(5)

,record,date,ssn,firstname,lastname,dob,homephone,fraud_label,fulladdress,ndob,...,napps_sa_1,napps_sa_3,napps_sa_7,napps_sa_14,napps_sa_30,v_sa_3,v_sa_7,v_sa_14,v_sa_30,ssnaddress_diff
0,1,1970-01-01 00:00:00.020160101,379070012,XRRAMMTR,SMJETJMJ,19070626,1797504115,0,6861 EUTST PL 2765,XRRAMMTRSMJETJMJ19070626,...,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
1,2,1970-01-01 00:00:00.020160101,387482503,MAMSTUJR,RTTEMRRR,19340615,4164239415,1,7280 URASA PL 57169,MAMSTUJRRTTEMRRR19340615,...,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
2,3,1970-01-01 00:00:00.020160101,200332444,SZMMUJEZS,EUSEZRAE,19070626,216537580,0,5581 RSREX LN 56721,SZMMUJEZSEUSEZRAE19070626,...,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
3,4,1970-01-01 00:00:00.020160101,747451317,SJJZSXRSZ,ETJXTXXS,19440430,132144161,0,1387 UJZXJ RD 35286,SJJZSXRSZETJXTXXS19440430,...,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
4,5,1970-01-01 00:00:00.020160101,24065868,SSSXUEJMS,SSUUJXUZ,19980315,6101082272,0,279 EAASA WY 3173,SSSXUEJMSSSUUJXUZ19980315,...,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0

In [86]:
vars_s = vars_s.drop(columns =       ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_a = vars_a.drop(columns =       ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_ndob = vars_ndob.drop(columns = ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_p = vars_p.drop(columns =       ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_sa = vars_sa.drop(columns =     ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_nda = vars_nda.drop(columns =   ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_pa = vars_pa.drop(columns =     ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_ndp = vars_ndp.drop(columns =   ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_ap = vars_ap.drop(columns =     ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_ps = vars_ps.drop(columns =     ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_nds = vars_nds.drop(columns =   ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_snd = vars_snd.drop(columns =   ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_fns = vars_fns.drop(columns =   ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])
vars_lns = vars_lns.drop(columns =   ['apps_by_s','apps_by_a','apps_by_p','apps_by_ndob','apps_by_sa','apps_by_nda','apps_by_pa','apps_by_ndp', \
                                  'apps_by_ap','apps_by_ps','apps_by_nds','apps_by_snd','apps_by_fns','apps_by_lns'])

In [87]:
vars_s.head(20)

,record,date,ssn,firstname,lastname,dob,homephone,fraud_label,fulladdress,ndob,napps_s_1,napps_s_3,napps_s_7,napps_s_14,napps_s_30,v_ssn_3,v_ssn_7,v_ssn_14,v_ssn_30,ssn_diff
0,1,1970-01-01 00:00:00.020160101,379070012,XRRAMMTR,SMJETJMJ,19070626,1797504115,0,6861 EUTST PL 2765,XRRAMMTRSMJETJMJ19070626,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
1,2,1970-01-01 00:00:00.020160101,387482503,MAMSTUJR,RTTEMRRR,19340615,4164239415,1,7280 URASA PL 57169,MAMSTUJRRTTEMRRR19340615,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
2,3,1970-01-01 00:00:00.020160101,200332444,SZMMUJEZS,EUSEZRAE,19070626,216537580,0,5581 RSREX LN 56721,SZMMUJEZSEUSEZRAE19070626,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
3,4,1970-01-01 00:00:00.020160101,747451317,SJJZSXRSZ,ETJXTXXS,19440430,132144161,0,1387 UJZXJ RD 35286,SJJZSXRSZETJXTXXS19440430,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
4,5,1970-01-01 00:00:00.020160101,24065868,SSSXUEJMS,SSUUJXUZ,19980315,6101082272,0,279 EAASA WY 3173,SSSXUEJMSSSUUJXUZ19980315,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
5,6,1970-01-01 00:00:00.020160101,922264214,XEEJJSTER,ERJSAXA,19480613,5742016319,0,4322 USJXU LN 8391,XEEJJSTERERJSAXA19480613,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
6,7,1970-01-01 00:00:00.020160101,415812149,XZJRJUSRR,STSMJRUM,19640318,7697396312,0,478 EEXUM LN 41640,XZJRJUSRRSTSMJRUM19640318,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
7,8,1970-01-01 00:00:00.020160101,373752050,EJMRRSUXR,AMTZXRU,19190528,2727421586,0,8906 UUAJ PL 60567,EJMRRSUXRAMTZXRU19190528,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
8,9,1970-01-01 00:00:00.020160101,769970791,RXTSZJATS,RSXMRJME,19900314,5520652307,0,8266 SSEAR RD 37934,RXTSZJATSRSXMRJME19900314,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
9,10,1970-01-01 00:00:00.020160101,732119085,EREMTZXXA,EXMMSEXT,19750127,3749451123,0,9166 XXSAZ PL 93751,EREMTZXXAEXMMSEXT19750127,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
10,11,1970-01-01 00:00:00.020160101,999999999,UZZSMXSEE,USJZUSA,19400126,3026547212,0,726 UMTXU ST 92129,UZZSMXSEEUSJZUSA19400126,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0
11,23,1970-01-01 00:00:00.020160101,999999999,ETXMUSZEM,UJMAMEU,19580830,5568704443,0,3387 STRUM WY 45982,ETXMUSZEMUJMAMEU19580830,2.0,2.0,2.0,2.0,2.0,0.333333,0.142857,0.071429,0.033333,0.0
12,65,1970-01-01 00:00:00.020160101,999999999,STUMMAMTS,SSJXTUJM,19070626,9999999999,0,6393 UEJEA LN 41640,STUMMAMTSSSJXTUJM19070626,3.0,3.0,3.0,3.0,3.0,0.333333,0.142857,0.071429,0.033333,0.0
13,69,1970-01-01 00:00:00.020160101,999999999,UUZAJXZMT,SRAAMZXU,20110831,5490098836,0,2557 URRXS DR 98407,UUZAJXZMTSRAAMZXU20110831,4.0,4.0,4.0,4.0,4.0,0.333333,0.142857,0.071429,0.033333,0.0
14,75,1970-01-01 00:00:00.020160101,999999999,AUATMMZX,UUUTAZR,19760625,2382673773,0,30 ETXRM ST 38402,AUATMMZXUUUTAZR19760625,5.0,5.0,5.0,5.0,5.0,0.333333,0.142857,0.071429,0.033333,0.0
15,284,1970-01-01 00:00:00.020160101,999999999,MSJUZSMZJ,UXMTEZUT,19070626,153492955,0,356 UZSRE AVE 74187,MSJUZSMZJUXMTEZUT19070626,6.0,6.0,6.0,6.0,6.0,0.333333,0.142857,0.071429,0.033333,0.0
16,381,1970-01-01 00:00:00.020160101,999999999,XRJSMRRRT,RMRXAMX,19070626,3181686949,0,9769 UAMZJ DR 52351,XRJSMRRRTRMRXAMX19070626,7.0,7.0,7.0,7.0,7.0,0.333333,0.142857,0.071429,0.033333,0.0
17,421,1970-01-01 00:00:00.020160101,999999999,XRXMTMZEZ,SZRXXJMX,19970721,316681200,0,5854 RXRXX PL 34957,XRXMTMZEZSZRXXJMX19970721,8.0,8.0,8.0,8.0,8.0,0.333333,0.142857,0.071429,0.033333,0.0
18,447,1970-01-01 00:00:00.020160101,999999999,RRZUZUSX,ESZRRRAA,19110729,5350782211,0,8970 AXME RD 48333,RRZUZUSXESZRRRAA19110729,9.0,9.0,9.0,9.0,9.0,0.333333,0.142857,0.071429,0.033333,0.0
19,469,1970-01-01 00:00:00.020160101,999999999,XETRJXESR,SSJXTUJM,19700418,2503172355,0,6995 RMSST CT 48162,XETRJXESRSSJXTUJM19700418,10.0,10.0,10.0,10.0,10.0,0.333333,0.142857,0.071429,0.033333,0.0

In [88]:
vars_s.shape

(1000000, 20)

In [89]:
all_vars = vars_s.merge(vars_a, on = 'record').merge(vars_ndob, on = 'record').merge(vars_p, on = 'record').merge(vars_sa, on = 'record') \
                 .merge(vars_nda, on = 'record').merge(vars_pa, on = 'record').merge(vars_ndp, on = 'record').merge(vars_ap, on = 'record') \
                 .merge(vars_ps, on = 'record').merge(vars_nds, on = 'record').merge(vars_snd, on = 'record') \
                 .merge(vars_fns, on = 'record').merge(vars_lns, on = 'record').merge(y, on = 'record')
all_vars.sort_values(by = 'record', inplace = True)
all_vars.head(5)

,record,date_x,ssn_x,firstname_x,lastname_x,dob_x,homephone_x,fraud_label_x,fulladdress_x,ndob_x,...,napps_lns_3,napps_lns_7,napps_lns_14,napps_lns_30,v_lns_3,v_lns_7,v_lns_14,v_lns_30,lastnamessn_diff,fraud_label
0,1,1970-01-01 00:00:00.020160101,379070012,XRRAMMTR,SMJETJMJ,19070626,1797504115,0,6861 EUTST PL 2765,XRRAMMTRSMJETJMJ19070626,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0
1,2,1970-01-01 00:00:00.020160101,387482503,MAMSTUJR,RTTEMRRR,19340615,4164239415,1,7280 URASA PL 57169,MAMSTUJRRTTEMRRR19340615,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,1
2,3,1970-01-01 00:00:00.020160101,200332444,SZMMUJEZS,EUSEZRAE,19070626,216537580,0,5581 RSREX LN 56721,SZMMUJEZSEUSEZRAE19070626,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0
3,4,1970-01-01 00:00:00.020160101,747451317,SJJZSXRSZ,ETJXTXXS,19440430,132144161,0,1387 UJZXJ RD 35286,SJJZSXRSZETJXTXXS19440430,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0
4,5,1970-01-01 00:00:00.020160101,24065868,SSSXUEJMS,SSUUJXUZ,19980315,6101082272,0,279 EAASA WY 3173,SSSXUEJMSSSUUJXUZ19980315,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0

In [90]:
all_vars = all_vars.drop(columns = ['date_x', 'ssn_x', 'firstname_x', 'lastname_x', 'homephone_x', 'fulladdress_x', 'ndob_x'])
all_vars = all_vars.drop(columns = ['date_y', 'ssn_y', 'firstname_y', 'lastname_y', 'homephone_y', 'fulladdress_y', 'ndob_y'])
all_vars = all_vars.drop(columns = ['dob_x', 'fraud_label_x'])

In [91]:
all_vars.head(5)

,record,napps_s_1,napps_s_3,napps_s_7,napps_s_14,napps_s_30,v_ssn_3,v_ssn_7,v_ssn_14,v_ssn_30,...,napps_lns_3,napps_lns_7,napps_lns_14,napps_lns_30,v_lns_3,v_lns_7,v_lns_14,v_lns_30,lastnamessn_diff,fraud_label
0,1,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0
1,2,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,1
2,3,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0
3,4,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0
4,5,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0

In [92]:
pd.options.display.max_rows = 250

In [93]:
all_vars.isnull().sum()

record               0
napps_s_1            0
napps_s_3            0
napps_s_7            0
napps_s_14           0
napps_s_30           0
v_ssn_3              0
v_ssn_7              0
v_ssn_14             0
v_ssn_30             0
ssn_diff             0
dob_y                0
fraud_label_y        0
napps_a_1            0
napps_a_3            0
napps_a_7            0
napps_a_14           0
napps_a_30           0
v_a_3                0
v_a_7                0
v_a_14               0
v_a_30               0
address_diff         0
napps_ndob_1         0
napps_ndob_3         0
napps_ndob_7         0
napps_ndob_14        0
napps_ndob_30        0
v_ndob_3             0
v_ndob_7             0
v_ndob_14            0
v_ndob_30            0
ndob_diff            0
dob_y                0
fraud_label_y        0
napps_p_1            0
napps_p_3            0
napps_p_7            0
napps_p_14           0
napps_p_30           0
v_p_3                0
v_p_7                0
v_p_14               0
v_p_30               0
phone_diff           0
napps_sa_1           0
napps_sa_3           0
napps_sa_7           0
napps_sa_14          0
napps_sa_30          0
v_sa_3               0
v_sa_7               0
v_sa_14              0
v_sa_30              0
ssnaddress_diff      0
dob_y                0
fraud_label_y        0
napps_nda_1          0
napps_nda_3          0
napps_nda_7          0
napps_nda_14         0
napps_nda_30         0
v_nda_3              0
v_nda_7              0
v_nda_14             0
v_nda_30             0
ndobaddress_diff     0
napps_pa_1           0
napps_pa_3           0
napps_pa_7           0
napps_pa_14          0
napps_pa_30          0
v_pa_3               0
v_pa_7               0
v_pa_14              0
v_pa_30              0
phoneaddress_diff    0
dob_y                0
fraud_label_y        0
napps_ndp_1          0
napps_ndp_3          0
napps_ndp_7          0
napps_ndp_14         0
napps_ndp_30         0
v_ndp_3              0
v_ndp_7              0
v_ndp_14             0
v_ndp_30             0
ndobphone_diff       0
napps_ap_1           0
napps_ap_3           0
napps_ap_7           0
napps_ap_14          0
napps_ap_30          0
v_ap_3               0
v_ap_7               0
v_ap_14              0
v_ap_30              0
addressphone_diff    0
dob_y                0
fraud_label_y        0
napps_ps_1           0
napps_ps_3           0
napps_ps_7           0
napps_ps_14          0
napps_ps_30          0
v_ps_3               0
v_ps_7               0
v_ps_14              0
v_ps_30              0
phonessn_diff        0
napps_nds_1          0
napps_nds_3          0
napps_nds_7          0
napps_nds_14         0
napps_nds_30         0
v_nds_3              0
v_nds_7              0
v_nds_14             0
v_nds_30             0
ndobssn_diff         0
dob_y                0
fraud_label_y        0
napps_snd_1          0
napps_snd_3          0
napps_snd_7          0
napps_snd_14         0
napps_snd_30         0
v_snd_3              0
v_snd_7              0
v_snd_14             0
v_snd_30             0
ssnndob_diff         0
napps_fns_1          0
napps_fns_3          0
napps_fns_7          0
napps_fns_14         0
napps_fns_30         0
v_fns_3              0
v_fns_7              0
v_fns_14             0
v_fns_30             0
fnssn_diff           0
dob_y                0
fraud_label_y        0
napps_lns_1          0
napps_lns_3          0
napps_lns_7          0
napps_lns_14         0
napps_lns_30         0
v_lns_3              0
v_lns_7              0
v_lns_14             0
v_lns_30             0
lastnamessn_diff     0
fraud_label          0
dtype: int64

In [94]:
all_vars_final = all_vars.fillna(0)

In [95]:
all_vars_final = all_vars_final.drop(columns = ['fraud_label_y'])

In [96]:
all_vars_final = all_vars_final.drop(columns = ['dob_y'])

In [97]:
all_vars_final.isnull().sum()

record               0
napps_s_1            0
napps_s_3            0
napps_s_7            0
napps_s_14           0
napps_s_30           0
v_ssn_3              0
v_ssn_7              0
v_ssn_14             0
v_ssn_30             0
ssn_diff             0
napps_a_1            0
napps_a_3            0
napps_a_7            0
napps_a_14           0
napps_a_30           0
v_a_3                0
v_a_7                0
v_a_14               0
v_a_30               0
address_diff         0
napps_ndob_1         0
napps_ndob_3         0
napps_ndob_7         0
napps_ndob_14        0
napps_ndob_30        0
v_ndob_3             0
v_ndob_7             0
v_ndob_14            0
v_ndob_30            0
ndob_diff            0
napps_p_1            0
napps_p_3            0
napps_p_7            0
napps_p_14           0
napps_p_30           0
v_p_3                0
v_p_7                0
v_p_14               0
v_p_30               0
phone_diff           0
napps_sa_1           0
napps_sa_3           0
napps_sa_7           0
napps_sa_14          0
napps_sa_30          0
v_sa_3               0
v_sa_7               0
v_sa_14              0
v_sa_30              0
ssnaddress_diff      0
napps_nda_1          0
napps_nda_3          0
napps_nda_7          0
napps_nda_14         0
napps_nda_30         0
v_nda_3              0
v_nda_7              0
v_nda_14             0
v_nda_30             0
ndobaddress_diff     0
napps_pa_1           0
napps_pa_3           0
napps_pa_7           0
napps_pa_14          0
napps_pa_30          0
v_pa_3               0
v_pa_7               0
v_pa_14              0
v_pa_30              0
phoneaddress_diff    0
napps_ndp_1          0
napps_ndp_3          0
napps_ndp_7          0
napps_ndp_14         0
napps_ndp_30         0
v_ndp_3              0
v_ndp_7              0
v_ndp_14             0
v_ndp_30             0
ndobphone_diff       0
napps_ap_1           0
napps_ap_3           0
napps_ap_7           0
napps_ap_14          0
napps_ap_30          0
v_ap_3               0
v_ap_7               0
v_ap_14              0
v_ap_30              0
addressphone_diff    0
napps_ps_1           0
napps_ps_3           0
napps_ps_7           0
napps_ps_14          0
napps_ps_30          0
v_ps_3               0
v_ps_7               0
v_ps_14              0
v_ps_30              0
phonessn_diff        0
napps_nds_1          0
napps_nds_3          0
napps_nds_7          0
napps_nds_14         0
napps_nds_30         0
v_nds_3              0
v_nds_7              0
v_nds_14             0
v_nds_30             0
ndobssn_diff         0
napps_snd_1          0
napps_snd_3          0
napps_snd_7          0
napps_snd_14         0
napps_snd_30         0
v_snd_3              0
v_snd_7              0
v_snd_14             0
v_snd_30             0
ssnndob_diff         0
napps_fns_1          0
napps_fns_3          0
napps_fns_7          0
napps_fns_14         0
napps_fns_30         0
v_fns_3              0
v_fns_7              0
v_fns_14             0
v_fns_30             0
fnssn_diff           0
napps_lns_1          0
napps_lns_3          0
napps_lns_7          0
napps_lns_14         0
napps_lns_30         0
v_lns_3              0
v_lns_7              0
v_lns_14             0
v_lns_30             0
lastnamessn_diff     0
fraud_label          0
dtype: int64

In [98]:
all_vars_final.head()

,record,napps_s_1,napps_s_3,napps_s_7,napps_s_14,napps_s_30,v_ssn_3,v_ssn_7,v_ssn_14,v_ssn_30,...,napps_lns_3,napps_lns_7,napps_lns_14,napps_lns_30,v_lns_3,v_lns_7,v_lns_14,v_lns_30,lastnamessn_diff,fraud_label
0,1,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0
1,2,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,1
2,3,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0
3,4,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0
4,5,1.0,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,...,1.0,1.0,1.0,1.0,0.333333,0.142857,0.071429,0.033333,0.0,0

In [99]:
all_vars_final.to_csv('all_vars.csv', index = False)

In [100]:
all_vars_final.shape

(1000000, 142)

In [104]:
table1=all_vars_final.describe()

In [102]:
all_vars_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000000 entries, 0 to 999999
Columns: 142 entries, record to fraud_label
dtypes: float64(140), int64(2)
memory usage: 1.1 GB

In [103]:
end_time = pd.datetime.now()
print(start_time)
print(end_time)
print(end_time - start_time)

2020-02-29 00:49:07.888957
2020-02-29 20:29:47.757711
19:40:39.868754

In [105]:
table1.to_csv("Variable Description.csv")